import type { MetricDefinition, MetricSourceTier } from "./metric-locator-types";

export const METRIC_SOURCE_ORDER: MetricSourceTier[] = [
  "standard-sec-xbrl",
  "filing-custom-xbrl",
  "filing-html-table",
  "filing-text",
  "earnings-release-exhibit",
  "investor-presentation",
];

const preferredSources = [...METRIC_SOURCE_ORDER];

export const SHELL_METRIC_DEFINITIONS: MetricDefinition[] = [
  {
    id: "operating-cash-flow",
    displayName: { zh: "经营现金流", en: "Operating cash flow" },
    aliases: ["cash flow from operating activities", "CFFO", "operating cash flow"],
    acceptedUnits: ["USD"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [
      {
        taxonomy: "ifrs-full",
        concept: "CashFlowsFromUsedInOperatingActivities",
        definitionKey: "reported-operating-cash-flow",
      },
    ],
    customConcepts: [],
    textRules: [],
    requiredInputs: [],
    validationRules: [
      "Use a full fiscal-year duration fact.",
      "Preserve the issuer currency and cash-flow-statement sign.",
    ],
    acceptedDefinitionKeys: ["reported-operating-cash-flow"],
    valueKind: "currency",
    visible: false,
  },
  {
    id: "production",
    displayName: { zh: "油气产量", en: "Production" },
    aliases: [
      "production available for sale",
      "oil and gas production",
      "total production available for sale",
    ],
    acceptedUnits: ["kboe/d"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [],
    customConcepts: [],
    textRules: [
      {
        sourceTier: "filing-html-table",
        pattern:
          /Production available for sale[\s\S]{0,900}?Thousand boe\/d\s+2025\s+2024\s+2023[\s\S]{0,500}?Total\s+([\d,]+)\s+[\d,]+\s+[\d,]+/i,
        scale: 1,
        unit: "kboe/d",
        section: "Oil and gas information",
        table: "Production available for sale",
        row: "Total",
        rawLabel: "Total production available for sale",
        accountingDefinition:
          "Oil and gas production available for sale, including subsidiaries and Shell share of joint ventures and associates.",
        definitionKey: "shell-production-available-for-sale",
        confidence: 0.97,
      },
    ],
    requiredInputs: [],
    validationRules: [
      "Require the consolidated Total row.",
      "Require thousand barrels of oil equivalent per day.",
      "Do not substitute reserves or annual million-boe totals.",
    ],
    acceptedDefinitionKeys: ["shell-production-available-for-sale"],
    valueKind: "volume",
    visible: true,
    minimum: 0,
    maximum: 20_000,
  },
  {
    id: "realized-prices",
    displayName: { zh: "实现价格", en: "Realized prices" },
    aliases: [
      "average realised price",
      "average realized price",
      "crude oil and natural gas liquids price",
    ],
    acceptedUnits: ["USD/bbl"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [],
    customConcepts: [],
    textRules: [
      {
        sourceTier: "filing-html-table",
        pattern:
          /Average realised price by geographical area\s+Crude oil and natural gas liquids\s+\$\/barrel\s+2025[\s\S]{0,500}?Europe\s+([\d.]+)/i,
        scale: 1,
        unit: "USD/bbl",
        currency: "USD",
        section: "Oil and gas information",
        table: "Average realised price by geographical area",
        row: "Europe — Shell subsidiaries — crude oil and natural gas liquids",
        rawLabel: "Europe, Shell subsidiaries",
        accountingDefinition:
          "Average realised liquids price for the specified geography and ownership column; not a group-wide blended price.",
        definitionKey: "shell-realized-liquids-price-geography",
        confidence: 0.88,
      },
    ],
    requiredInputs: [],
    validationRules: [
      "Retain product, geography, and ownership context.",
      "Do not present one geographic row as a group-wide blended realization.",
      "Require USD per barrel.",
    ],
    acceptedDefinitionKeys: ["shell-realized-liquids-price-geography"],
    valueKind: "rate",
    visible: true,
    minimum: 0,
    maximum: 500,
  },
  {
    id: "lng",
    displayName: { zh: "LNG 销量", en: "LNG volumes" },
    aliases: ["LNG sales volumes", "LNG volumes", "liquefaction volumes"],
    acceptedUnits: ["million tonnes"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [],
    customConcepts: [],
    textRules: [
      {
        sourceTier: "filing-html-table",
        pattern: /LNG sales volumes \(million tonnes\)\s+([\d.]+)\s+[\d.]+\s+[\d.]+/i,
        scale: 1,
        unit: "million tonnes",
        section: "Integrated Gas",
        table: "Integrated Gas data table",
        row: "LNG sales volumes",
        rawLabel: "LNG sales volumes (million tonnes)",
        accountingDefinition:
          "LNG sales volumes, including Shell-produced and third-party purchased LNG sold through the portfolio.",
        definitionKey: "shell-lng-sales-volumes",
        confidence: 0.98,
      },
    ],
    requiredInputs: [],
    validationRules: [
      "Distinguish sales volumes from liquefaction volumes.",
      "Require million tonnes and the fiscal-year column.",
    ],
    acceptedDefinitionKeys: ["shell-lng-sales-volumes"],
    valueKind: "volume",
    visible: true,
    minimum: 0,
    maximum: 500,
  },
  {
    id: "refining-margin",
    displayName: { zh: "炼化利润率", en: "Refining margins" },
    aliases: ["global indicative refining margin", "indicative refining margin", "refining margin"],
    acceptedUnits: ["USD/bbl"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [],
    customConcepts: [],
    textRules: [
      {
        sourceTier: "filing-html-table",
        pattern:
          /Global indicative refining margin\s+\$\/bbl\s+2025\s+2024\s+2023\s+Indicative refining margin\s+([\d.]+)/i,
        scale: 1,
        unit: "USD/bbl",
        currency: "USD",
        section: "Chemicals and Products",
        table: "Global indicative refining margin",
        row: "Indicative refining margin",
        rawLabel: "Indicative refining margin",
        accountingDefinition:
          "Shell global indicative gross refining unit margin based on benchmark price markers; actual realised margins may differ.",
        definitionKey: "shell-global-indicative-refining-margin",
        confidence: 0.96,
      },
    ],
    requiredInputs: [],
    validationRules: [
      "Preserve the word indicative.",
      "Do not relabel the benchmark as actual realised refining margin.",
      "Require USD per barrel.",
    ],
    acceptedDefinitionKeys: ["shell-global-indicative-refining-margin"],
    valueKind: "rate",
    visible: true,
    minimum: -100,
    maximum: 200,
  },
  {
    id: "segment-earnings",
    displayName: { zh: "分部收益", en: "Segment earnings" },
    aliases: ["segment adjusted earnings", "adjusted earnings by segment"],
    acceptedUnits: ["USD"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [],
    customConcepts: [
      {
        taxonomy: "shel",
        concept: "AdjustedEarnings",
        definitionKey: "shell-segment-adjusted-earnings-total",
      },
    ],
    textRules: [],
    requiredInputs: [],
    validationRules: [
      "Select the consolidated context without a segment dimension.",
      "Preserve that this is the CODM Adjusted Earnings measure including non-controlling interests.",
      "Do not equate it with IFRS segment net income.",
    ],
    acceptedDefinitionKeys: ["shell-segment-adjusted-earnings-total"],
    valueKind: "currency",
    visible: true,
    minimum: -200_000_000_000,
    maximum: 300_000_000_000,
  },
  {
    id: "cash-capex",
    displayName: { zh: "现金资本开支", en: "Cash capital expenditure" },
    aliases: ["cash capital expenditure", "cash capex", "capital expenditure paid in cash"],
    acceptedUnits: ["USD"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [
      {
        taxonomy: "ifrs-full",
        concept: "PurchaseOfPropertyPlantAndEquipment",
        definitionKey: "cash-purchases-property-plant-equipment",
      },
    ],
    customConcepts: [
      {
        taxonomy: "shel",
        concept: "CashOutflowForTotalCashCapitalExpenditure",
        definitionKey: "issuer-reported-cash-capex",
      },
    ],
    textRules: [
      {
        sourceTier: "filing-html-table",
        pattern:
          /Free cash flow\*\s+26,052\s+39,533\s+36,457\s+Cash capital expenditure\s+([\d,]+)/i,
        scale: 1_000_000,
        unit: "USD",
        currency: "USD",
        section: "Group results",
        table: "Key financial data",
        row: "Cash capital expenditure",
        rawLabel: "Cash capital expenditure",
        accountingDefinition: "Shell cash capital expenditure non-GAAP measure.",
        definitionKey: "issuer-reported-cash-capex",
        confidence: 0.94,
      },
    ],
    requiredInputs: [],
    validationRules: [
      "Use a full-year cash outflow.",
      "Do not substitute accounting capital expenditure or total investing cash flow.",
      "Normalize the reported USD millions to USD.",
    ],
    acceptedDefinitionKeys: [
      "cash-purchases-property-plant-equipment",
      "issuer-reported-cash-capex",
    ],
    valueKind: "currency",
    visible: true,
    minimum: 0,
    maximum: 500_000_000_000,
  },
  {
    id: "fcf",
    displayName: { zh: "自由现金流", en: "Free cash flow" },
    aliases: ["free cash flow", "FCF", "CFFO less cash capex"],
    acceptedUnits: ["USD"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [],
    customConcepts: [],
    textRules: [
      {
        sourceTier: "filing-html-table",
        pattern:
          /Cash flow from investing activities\s+\([\d,]+\)\s+\([\d,]+\)\s+\([\d,]+\)\s+Free cash flow\*\s+([\d,]+)/i,
        scale: 1_000_000,
        unit: "USD",
        currency: "USD",
        section: "Group results",
        table: "Key financial data",
        row: "Free cash flow",
        rawLabel: "Free cash flow",
        accountingDefinition:
          "Shell reported free cash flow equals cash flow from operating activities plus cash flow from investing activities.",
        definitionKey: "shell-reported-fcf-cffo-plus-investing",
        confidence: 0.98,
      },
    ],
    derivationFormula: "Operating cash flow - cash capital expenditure",
    requiredInputs: ["operating-cash-flow", "cash-capex"],
    validationRules: [
      "Calculate only operating cash flow minus cash capital expenditure.",
      "Reject issuer FCF definitions based on total investing cash flow.",
      "Require both inputs for the same company, period, and currency.",
    ],
    acceptedDefinitionKeys: ["ocf-less-cash-capex"],
    valueKind: "currency",
    visible: true,
  },
  {
    id: "net-debt",
    displayName: { zh: "净债务", en: "Net debt" },
    aliases: ["net debt", "adjusted net debt", "gearing net debt"],
    acceptedUnits: ["USD"],
    periodRule: "fiscal-year-end-instant",
    preferredSources,
    standardConcepts: [],
    customConcepts: [],
    textRules: [
      {
        sourceTier: "filing-html-table",
        pattern:
          /Net debt\* at December 31 \[E\]\s+([\d,]+)\s+[\d,]+\s+[\d,]+/i,
        scale: 1_000_000,
        unit: "USD",
        currency: "USD",
        section: "Liquidity and capital resources",
        table: "Key financial data",
        row: "Net debt at December 31",
        rawLabel: "Net debt",
        accountingDefinition:
          "Current and non-current debt less cash, adjusted for debt hedging derivatives and associated collateral.",
        definitionKey: "issuer-reported-net-debt",
        confidence: 0.98,
      },
    ],
    requiredInputs: [],
    validationRules: [
      "Use the period-end balance.",
      "Preserve Shell's derivative and collateral adjustments.",
      "Do not replace reported net debt with debt less cash when definitions differ.",
    ],
    acceptedDefinitionKeys: ["issuer-reported-net-debt"],
    valueKind: "currency",
    visible: true,
    minimum: -100_000_000_000,
    maximum: 500_000_000_000,
  },
  {
    id: "dividends",
    displayName: { zh: "现金股息", en: "Dividends" },
    aliases: ["dividends paid", "cash dividends", "dividends paid to shareholders"],
    acceptedUnits: ["USD"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [
      {
        taxonomy: "ifrs-full",
        concept: "DividendsPaidToEquityHoldersOfParentClassifiedAsFinancingActivities",
        definitionKey: "cash-dividends-to-parent-shareholders",
      },
      {
        taxonomy: "ifrs-full",
        concept: "DividendsPaidOrdinaryShares",
        definitionKey: "cash-dividends-to-parent-shareholders",
      },
    ],
    customConcepts: [],
    textRules: [],
    requiredInputs: [],
    validationRules: [
      "Use cash dividends paid to Shell plc shareholders.",
      "Exclude dividends to non-controlling interests.",
      "Use a full fiscal-year duration fact.",
    ],
    acceptedDefinitionKeys: [
      "cash-dividends-to-parent-shareholders",
    ],
    valueKind: "currency",
    visible: true,
    minimum: 0,
    maximum: 100_000_000_000,
  },
  {
    id: "share-buybacks",
    displayName: { zh: "股票回购", en: "Share buybacks" },
    aliases: ["share repurchases", "share buybacks", "payments to acquire or redeem shares"],
    acceptedUnits: ["USD"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [
      {
        taxonomy: "ifrs-full",
        concept: "PaymentsToAcquireOrRedeemEntitysShares",
        definitionKey: "cash-share-buybacks",
      },
    ],
    customConcepts: [],
    textRules: [],
    requiredInputs: [],
    validationRules: [
      "Use cash paid to acquire or redeem the issuer's shares.",
      "Do not substitute the retained-earnings charge or programme authorization.",
      "Use a full fiscal-year duration fact.",
    ],
    acceptedDefinitionKeys: ["cash-share-buybacks"],
    valueKind: "currency",
    visible: true,
    minimum: 0,
    maximum: 200_000_000_000,
  },
  {
    id: "major-projects",
    displayName: { zh: "重大项目", en: "Major projects" },
    aliases: ["major projects", "project start-up", "projects delivered on schedule"],
    acceptedUnits: ["projects"],
    periodRule: "fiscal-year-duration",
    preferredSources,
    standardConcepts: [],
    customConcepts: [],
    textRules: [
      {
        sourceTier: "filing-text",
        pattern:
          /successful start-up of (\d+) projects, notably Whale in the Gulf of America, Penguins in the UK, Mero-4 in Brazil and the first export cargo from LNG Canada/i,
        scale: 1,
        unit: "projects",
        section: "Projects & Technology",
        row: "2025 performance",
        rawLabel: "Successful start-up of projects",
        accountingDefinition:
          "Count of projects successfully started during 2025; named examples are Whale, Penguins, Mero-4, and LNG Canada first cargo.",
        definitionKey: "shell-successful-project-startups",
        confidence: 0.95,
      },
    ],
    requiredInputs: [],
    validationRules: [
      "Require a completed start-up count, not a planned project pipeline.",
      "Retain the named-project context.",
    ],
    acceptedDefinitionKeys: ["shell-successful-project-startups"],
    valueKind: "count",
    visible: true,
    minimum: 0,
    maximum: 1_000,
  },
];

export const SHELL_REQUESTED_METRIC_IDS = SHELL_METRIC_DEFINITIONS
  .filter((definition) => definition.visible)
  .map((definition) => definition.id);

export function metricDefinition(id: string) {
  return SHELL_METRIC_DEFINITIONS.find((definition) => definition.id === id);
}
