import type { DiligenceLocale } from "./types";

export const CLARA_COPY = {
  en: {
    agent: "Clara",
    role: "Private Company Diligence Analyst",
    heading: "Which private company should Clara research",
    subheading: "Build an evidence-backed public-source diligence report from official records, company materials, and independent sources",
    assign: "Assign to Clara",
    confirmHeading: "Confirm the target company",
    selectTarget: "Select target",
    selectedTarget: "Selected",
    confirm: "Confirm target company",
    generate: "Generate Diligence Report",
    edit: "Start another review",
    downloadMarkdown: "Download Markdown",
    downloadPdf: "Download PDF",
    downloadingPdf: "Preparing PDF",
    evidenceCsv: "Evidence CSV",
    evidenceXlsx: "Evidence XLSX",
    claimsCsv: "Claims CSV",
    claimsXlsx: "Claims XLSX",
    riskCsv: "Risk CSV",
    insufficientIdentity: "Clara needs a website, location, or founder to distinguish this company from similarly named entities",
    insufficientEvidence: "Insufficient public information was identified to produce a reliable diligence report",
    identityInputHint: "Provide a company name, an official website, or both",
    quickInputHint: "Provide a company name, website, or both",
    narrowHeading: "Help Clara narrow it down",
    discoveryNoMatch: "Clara could not confidently identify the company from the information provided",
    notIdentified: "Not identified",
    legalName: "Legal entity name",
    unresolved: "Unresolved identity fields",
    lowConfidenceWebsite: "This appears to be a plausible match based on the available public information. You can confirm it as your research target, and Clara will continue verifying the company identity during research",
    targetConfirmed: "Target confirmed",
    companyReportedIdentity: "Website-derived identity · Company Reported",
    confidence: { High: "High", Medium: "Medium", Low: "Low" },
    disclosure: "This report is based solely on publicly accessible information and does not replace financial, legal, tax, operational, cybersecurity, or management due diligence",
    publicOnly: "Public-source review only · no document uploads in V1",
    back: "Back to FinBro",
    fields: {
      companyName: "Company name · Optional",
      website: "Company website · Optional",
      location: "Location · Optional",
      city: "City",
      state: "State",
      country: "Country",
      founder: "Founder or executive",
      industry: "Industry",
      objective: "Research objective",
      language: "Language",
      depth: "Report depth",
    },
  },
  zh: {
    agent: "Clara",
    role: "私营公司尽调分析师",
    heading: "Clara 应该研究哪家私营公司",
    subheading: "根据官方记录、公司材料和独立来源生成有证据支持的公开来源尽调报告",
    assign: "交给 Clara",
    confirmHeading: "确认目标公司",
    selectTarget: "选择目标",
    selectedTarget: "已选择",
    confirm: "确认目标公司",
    generate: "生成尽调报告",
    edit: "开始另一项审查",
    downloadMarkdown: "下载 Markdown",
    downloadPdf: "下载 PDF",
    downloadingPdf: "正在生成 PDF",
    evidenceCsv: "证据 CSV",
    evidenceXlsx: "证据 XLSX",
    claimsCsv: "主张 CSV",
    claimsXlsx: "主张 XLSX",
    riskCsv: "风险 CSV",
    insufficientIdentity: "Clara 需要公司网站、地点或创始人信息，以便与同名实体区分",
    insufficientEvidence: "未发现足够的公开信息来生成可靠的尽调报告",
    identityInputHint: "请输入公司名称、官方网站，或两者同时提供",
    quickInputHint: "填写公司名称、官网，或两者之一",
    narrowHeading: "帮助 Clara 缩小范围",
    discoveryNoMatch: "Clara 无法根据所提供的信息可靠识别该公司",
    notIdentified: "未识别",
    legalName: "法律实体名称",
    unresolved: "尚未确认的身份字段",
    lowConfidenceWebsite: "根据目前可获得的公开信息，这可能是您要调查的公司。您可以先确认该调查目标，Clara 会在后续调查中继续核实其法律实体与身份信息",
    targetConfirmed: "已确认目标公司",
    companyReportedIdentity: "网站提取的身份信息 · 公司自述",
    confidence: { High: "高", Medium: "中", Low: "低" },
    disclosure: "本报告仅基于公开可获取的信息，不能替代财务、法律、税务、运营、网络安全或管理层尽职调查",
    publicOnly: "仅限公开来源审查 · V1 不支持文件上传",
    back: "返回 FinBro",
    fields: {
      companyName: "公司名称 · 可选",
      website: "公司官网 · 可选",
      location: "地点 · 可选",
      city: "城市",
      state: "州或省",
      country: "国家",
      founder: "创始人或高管",
      industry: "行业",
      objective: "研究目标",
      language: "语言",
      depth: "报告深度",
    },
  },
} as const;

export const CLARA_PROGRESS = [
  { en: "Resolving the company identity", zh: "正在解析公司身份" },
  { en: "Reviewing candidate entities", zh: "正在审查候选实体" },
  { en: "Building the identity graph", zh: "正在构建身份图谱" },
  { en: "Checking official registrations", zh: "正在核查官方注册记录" },
  { en: "Reviewing the company website", zh: "正在审查公司网站" },
  { en: "Researching founders and management", zh: "正在研究创始人和管理层" },
  { en: "Checking financing records", zh: "正在核查融资记录" },
  { en: "Checking government contracts and public funding", zh: "正在核查政府合同和公共资金" },
  { en: "Reviewing intellectual property", zh: "正在审查知识产权" },
  { en: "Cross-checking customer and partner claims", zh: "正在交叉核对客户和合作伙伴主张" },
  { en: "Building the evidence register", zh: "正在构建证据登记册" },
  { en: "Reconciling conflicting claims", zh: "正在核对冲突主张" },
  { en: "Identifying information gaps", zh: "正在识别信息缺口" },
  { en: "Drafting the diligence report", zh: "正在起草尽调报告" },
  { en: "Validating references", zh: "正在验证参考资料" },
] as const;

export const CLARA_SECTION_TITLES = [
  ["01", "Executive Summary", "执行摘要"],
  ["02", "Entity Identification", "实体识别"],
  ["03", "Legal and Corporate Profile", "法律和公司概况"],
  ["04", "Business Model and Products", "商业模式和产品"],
  ["05", "Founders, Management, and Ownership", "创始人、管理层和所有权"],
  ["06", "Financing and Investors", "融资和投资者"],
  ["07", "Operating Footprint", "运营足迹"],
  ["08", "Customers, Partners, and Commercial Evidence", "客户、合作伙伴和商业证据"],
  ["09", "Government Contracts and Public Funding", "政府合同和公共资金"],
  ["10", "Intellectual Property", "知识产权"],
  ["11", "Licenses and Regulatory Status", "许可和监管状态"],
  ["12", "Litigation and Adverse Records", "诉讼和不利记录"],
  ["13", "Market and Industry Context", "市场和行业背景"],
  ["14", "Competitive Positioning", "竞争定位"],
  ["15", "Key Risks and Red Flags", "主要风险和红旗"],
  ["16", "Conflicting Information", "冲突信息"],
  ["17", "Information Gaps", "信息缺口"],
  ["18", "Follow-Up Due Diligence Questions", "后续尽调问题"],
  ["19", "Methodology and Limitations", "方法和局限性"],
  ["20", "References and Evidence Register", "参考资料和证据登记册"],
] as const;

export const label = (locale: DiligenceLocale, en: string, zh: string) => locale === "zh" ? zh : en;
