import type { SectorPack, SupportedSubindustry } from "./sector-types";

const energyPack: SectorPack = {
  id: "integrated-oil-gas",
  sector: "energy",
  sectorLabel: { zh: "能源", en: "Energy" },
  subindustryLabel: { zh: "综合石油与天然气", en: "Integrated Oil & Gas" },
  sicCodes: ["1311", "2911"],
  coreKpis: [
    {
      id: "production",
      label: { zh: "油气产量", en: "Production" },
      description: { zh: "权益口径产量及油气结构。", en: "Equity production and oil/gas mix." },
      availability: "notStandardized",
    },
    {
      id: "realized-prices",
      label: { zh: "实现价格", en: "Realized prices" },
      description: { zh: "相对基准油气价格的实现水平。", en: "Realizations versus oil and gas benchmarks." },
      availability: "notStandardized",
    },
    {
      id: "lng",
      label: { zh: "LNG 销量", en: "LNG volumes" },
      description: { zh: "液化量、销量和合同组合。", en: "Liquefaction, sales volumes, and contract mix." },
      availability: "notStandardized",
    },
    {
      id: "refining-margin",
      label: { zh: "炼化利润率", en: "Refining margins" },
      description: { zh: "炼厂利用率、价差与单位利润。", en: "Utilization, cracks, and unit margins." },
      availability: "notStandardized",
    },
    {
      id: "segment-earnings",
      label: { zh: "分部收益", en: "Segment earnings" },
      description: { zh: "管理层分部调整后收益及合并核对。", en: "Management segment adjusted earnings and consolidated reconciliation." },
      availability: "notStandardized",
    },
    {
      id: "cash-capex",
      label: { zh: "现金资本开支", en: "Cash capex" },
      description: { zh: "标准化申报中的现金购置固定资产。", en: "Cash purchases of property and equipment in standardized filings." },
      availability: "cashCapex",
    },
    {
      id: "fcf",
      label: { zh: "自由现金流", en: "Free cash flow" },
      description: { zh: "经营现金流减现金资本开支。", en: "Operating cash flow less cash capital expenditure." },
      availability: "freeCashFlow",
    },
    {
      id: "net-debt",
      label: { zh: "净债务", en: "Net debt" },
      description: { zh: "标准化债务减现金。", en: "Normalized debt less cash." },
      availability: "netDebt",
    },
    {
      id: "dividends",
      label: { zh: "现金股息", en: "Dividends" },
      description: { zh: "向母公司股东支付的现金股息。", en: "Cash dividends paid to parent-company shareholders." },
      availability: "notStandardized",
    },
    {
      id: "share-buybacks",
      label: { zh: "股票回购", en: "Share buybacks" },
      description: { zh: "用于收购或赎回发行人股份的现金。", en: "Cash used to acquire or redeem the issuer's shares." },
      availability: "notStandardized",
    },
    {
      id: "commodity-sensitivity",
      label: { zh: "商品价格敏感度", en: "Commodity sensitivity" },
      description: { zh: "油、气、LNG 与炼化价差对现金流的影响。", en: "Cash-flow exposure to oil, gas, LNG, and refining spreads." },
      availability: "notStandardized",
    },
    {
      id: "major-projects",
      label: { zh: "重大项目", en: "Major projects" },
      description: { zh: "投产时间、爬坡、预算及回报。", en: "Start-up timing, ramp, budget, and returns." },
      availability: "notStandardized",
    },
  ],
  researchQuestions: [
    { zh: "产量增长来自新项目还是高基数资产的自然递减？", en: "Is production growth driven by new projects or offset by base decline?" },
    { zh: "实现价格、炼化价差与 LNG 组合如何传导至经营现金流？", en: "How do realizations, refining spreads, and the LNG portfolio translate into operating cash flow?" },
    { zh: "资本开支中维护、增长与低碳项目各占多少？", en: "How much capital expenditure is maintenance, growth, or low-carbon investment?" },
    { zh: "股息和回购在下行情景中是否仍由自由现金流覆盖？", en: "Are dividends and buybacks covered by free cash flow in a downside case?" },
    { zh: "哪些重大项目的进度、成本或监管许可可能改变中期现金流？", en: "Which major-project schedules, costs, or permits could change medium-term cash flow?" },
  ],
  marketDrivers: [
    {
      id: "oil-balance",
      name: { zh: "全球原油供需与库存", en: "Global oil balance and inventories" },
      companyExposure: { zh: "上游实现价格、交易和营运资本。", en: "Upstream realizations, trading, and working capital." },
      implication: { zh: "库存累积通常压低价格与上游现金流，但下游价差可能部分对冲。", en: "Inventory builds generally pressure prices and upstream cash flow, partly offset by downstream spreads." },
      query: "global oil supply demand inventories Brent price upstream realizations",
    },
    {
      id: "lng-cycle",
      name: { zh: "LNG 供应扩张与合同结构", en: "LNG supply expansion and contract structure" },
      companyExposure: { zh: "液化、贸易、长期合同及目的地灵活性。", en: "Liquefaction, trading, long-term contracts, and destination flexibility." },
      implication: { zh: "新增产能可能压低现货溢价，同时提升组合优化的重要性。", en: "New capacity can compress spot premia while increasing the value of portfolio optimization." },
      query: "LNG supply capacity contracts pricing flexibility gas market",
    },
    {
      id: "refining-cycle",
      name: { zh: "炼化价差与利用率", en: "Refining cracks and utilization" },
      companyExposure: { zh: "炼厂利润、库存和产品需求。", en: "Refinery earnings, inventories, and product demand." },
      implication: { zh: "高价差可缓冲上游走弱，但持续性取决于库存与供应中断。", en: "Strong cracks can cushion upstream weakness, but durability depends on inventories and outages." },
      query: "refining margins crack spreads utilization product inventories",
    },
    {
      id: "capital-discipline",
      name: { zh: "资本纪律与股东分配", en: "Capital discipline and distributions" },
      companyExposure: { zh: "项目制资本开支、净债务、股息与回购。", en: "Project capex, net debt, dividends, and buybacks." },
      implication: { zh: "周期高点的资本纪律决定下行时的分配韧性。", en: "Peak-cycle capital discipline determines distribution resilience in a downturn." },
      query: "oil investment capex free cash flow net debt dividends buybacks",
    },
  ],
  peers: [
    { ticker: "XOM", cik: "0000034088", name: "Exxon Mobil", rationale: { zh: "全球综合能源与 LNG 可比。", en: "Global integrated energy and LNG comparator." } },
    { ticker: "CVX", cik: "0000093410", name: "Chevron", rationale: { zh: "上游与资本分配可比。", en: "Upstream and capital-allocation comparator." } },
    { ticker: "BP", cik: "0000313807", name: "BP", rationale: { zh: "欧洲综合能源转型可比。", en: "European integrated-energy transition comparator." } },
    { ticker: "TTE", cik: "0000879764", name: "TotalEnergies", rationale: { zh: "LNG 与综合能源组合可比。", en: "LNG and integrated portfolio comparator." } },
  ],
  valuation: {
    method: { zh: "情景 EV / 自由现金流", en: "Scenario EV / free cash flow" },
    formula: { zh: "模型隐含企业价值 = 情景自由现金流 × 假设 EV/FCF 倍数", en: "Model-implied enterprise value = scenario free cash flow × assumed EV/FCF multiple" },
    multipleLabel: "EV / FCF",
    multiples: { bear: 5, base: 7, bull: 9 },
    metric: "freeCashFlow",
    fallback: {
      method: {
        zh: "FCF 不可计算时使用情景 EV / 经营现金流",
        en: "Scenario EV / operating cash flow when FCF is unavailable",
      },
      formula: {
        zh: "模型隐含企业价值 = 情景经营现金流 × 假设 EV/经营现金流倍数；不把经营现金流称为 FCF",
        en: "Model-implied enterprise value = scenario operating cash flow × assumed EV/operating-cash-flow multiple; operating cash flow is not presented as FCF",
      },
      multipleLabel: "EV / OCF",
      multiples: { bear: 4, base: 6, bull: 8 },
      metric: "operatingCashFlow",
    },
  },
  risks: [
    { zh: "油气与炼化价格同步下跌。", en: "A synchronized decline in oil, gas, and refining prices." },
    { zh: "重大项目延误、超支或储量表现不及预期。", en: "Major-project delay, cost overrun, or reservoir underperformance." },
    { zh: "资本开支和分配在低价环境下推高净债务。", en: "Capex and distributions increase net debt in a low-price environment." },
    { zh: "碳政策、甲烷规则、诉讼或许可限制资产价值。", en: "Carbon policy, methane rules, litigation, or permitting constrain asset value." },
  ],
  catalysts: {
    operating: [
      { zh: "重大项目投产或爬坡快于计划。", en: "Major-project start-up or ramp ahead of plan." },
      { zh: "产量、LNG 销量或炼厂利用率改善。", en: "Improved production, LNG volumes, or refinery utilization." },
    ],
    financial: [
      { zh: "资本开支下降带动自由现金流拐点。", en: "A free-cash-flow inflection as capital expenditure declines." },
      { zh: "净债务下降支持股息或回购。", en: "Lower net debt supports dividends or buybacks." },
    ],
    regulatory: [
      { zh: "重大项目获得最终许可或税制明确。", en: "Final project approval or greater fiscal certainty." },
      { zh: "LNG、甲烷或碳政策发生实质变化。", en: "A material change in LNG, methane, or carbon policy." },
    ],
  },
  reportGuidance: [
    { zh: "将上游、LNG、炼化和资本配置分别讨论，避免只看合并营收。", en: "Separate upstream, LNG, refining, and capital allocation rather than relying on consolidated revenue." },
    { zh: "任何 FCF 只使用经营现金流减现金资本开支。", en: "Calculate FCF only as operating cash flow less cash capital expenditure." },
    { zh: "把商品价格假设、项目进度和分配政策作为独立敏感度。", en: "Treat commodity assumptions, project timing, and distribution policy as separate sensitivities." },
  ],
};

const semiconductorPack: SectorPack = {
  id: "semiconductors",
  sector: "technology",
  sectorLabel: { zh: "科技", en: "Technology" },
  subindustryLabel: { zh: "半导体", en: "Semiconductors" },
  sicCodes: ["3674"],
  coreKpis: [
    {
      id: "end-market",
      label: { zh: "终端市场收入", en: "End-market revenue" },
      description: { zh: "数据中心、游戏、汽车、工业等收入结构。", en: "Revenue mix across data center, gaming, automotive, industrial, and other end markets." },
      availability: "notStandardized",
    },
    {
      id: "ai-exposure",
      label: { zh: "AI / 数据中心敞口", en: "AI / data-center exposure" },
      description: { zh: "AI 训练、推理与网络产品收入暴露。", en: "Exposure to AI training, inference, and networking products." },
      availability: "notStandardized",
    },
    {
      id: "gross-margin",
      label: { zh: "毛利率", en: "Gross margin" },
      description: { zh: "营收减销售成本后占营收比例。", en: "Revenue less cost of revenue, divided by revenue." },
      availability: "grossMargin",
    },
    {
      id: "operating-margin",
      label: { zh: "营业利润率", en: "Operating margin" },
      description: { zh: "营业利润占营收比例。", en: "Operating income divided by revenue." },
      availability: "operatingMargin",
    },
    {
      id: "inventory",
      label: { zh: "库存", en: "Inventory" },
      description: { zh: "产品周期、供需与减值风险的资产负债表信号。", en: "Balance-sheet signal for product cycles, supply-demand, and write-down risk." },
      availability: "inventory",
    },
    {
      id: "utilization",
      label: { zh: "产能利用率", en: "Utilization" },
      description: { zh: "自有或供应链产能利用程度及周期信号。", en: "Utilization of owned or supply-chain capacity as a cycle signal." },
      availability: "notStandardized",
    },
    {
      id: "cash-capex",
      label: { zh: "现金资本开支", en: "Cash capex" },
      description: { zh: "现金购置固定资产；无晶圆厂模式也需观察基础设施投资。", en: "Cash purchases of property and equipment; relevant even for fabless infrastructure." },
      availability: "cashCapex",
    },
    {
      id: "fcf",
      label: { zh: "自由现金流", en: "Free cash flow" },
      description: { zh: "经营现金流减现金资本开支。", en: "Operating cash flow less cash capital expenditure." },
      availability: "freeCashFlow",
    },
    {
      id: "product-cycle",
      label: { zh: "产品周期", en: "Product cycle" },
      description: { zh: "架构更新、交付节奏、良率和供应约束。", en: "Architecture transitions, shipment cadence, yields, and supply constraints." },
      availability: "notStandardized",
    },
    {
      id: "customer-concentration",
      label: { zh: "客户集中度", en: "Customer concentration" },
      description: { zh: "前十大客户与云客户采购集中度。", en: "Concentration among major customers and cloud buyers." },
      availability: "notStandardized",
    },
    {
      id: "market-share",
      label: { zh: "市场份额", en: "Market share" },
      description: { zh: "按产品、加速器、CPU、网络或终端市场划分。", en: "Share by product, accelerator, CPU, networking, or end market." },
      availability: "notStandardized",
    },
  ],
  researchQuestions: [
    { zh: "增长来自单位出货、平均售价、组合升级还是供给释放？", en: "Is growth driven by units, average selling price, mix, or easing supply constraints?" },
    { zh: "AI / 数据中心需求有多少来自可持续使用量，多少来自建设周期？", en: "How much AI/data-center demand reflects durable utilization versus a buildout cycle?" },
    { zh: "产品换代、良率、封装与 HBM 供给如何影响毛利率？", en: "How do product transitions, yields, packaging, and HBM supply affect gross margin?" },
    { zh: "库存与预付款是否领先于需求放缓或供应改善？", en: "Do inventory and supply commitments lead a demand slowdown or supply improvement?" },
    { zh: "客户集中度、定制芯片和出口限制如何影响中期份额？", en: "How do customer concentration, custom silicon, and export controls affect medium-term share?" },
  ],
  marketDrivers: [
    {
      id: "ai-demand",
      name: { zh: "AI 与数据中心资本开支", en: "AI and data-center capital expenditure" },
      companyExposure: { zh: "加速器、网络、软件生态与供给分配。", en: "Accelerators, networking, software ecosystem, and supply allocation." },
      implication: { zh: "需求增长可抬升收入与组合，但高基数增加订单消化风险。", en: "Demand growth lifts revenue and mix, while a high base raises digestion risk." },
      query: "AI data center semiconductor demand accelerators logic memory sales",
    },
    {
      id: "capacity",
      name: { zh: "先进制程、封装与 HBM 产能", en: "Advanced-node, packaging, and HBM capacity" },
      companyExposure: { zh: "交付能力、成本、良率和产品爬坡。", en: "Shipment capacity, cost, yield, and product ramp." },
      implication: { zh: "产能扩张缓解瓶颈，但也可能在需求转弱时提高周期风险。", en: "Capacity expansion relieves bottlenecks but can amplify cyclicality if demand slows." },
      query: "300mm fab equipment advanced node HBM capacity packaging investment",
    },
    {
      id: "product-cycle",
      name: { zh: "产品迭代与竞争", en: "Product cadence and competition" },
      companyExposure: { zh: "性能、功耗、上市时间和生态粘性。", en: "Performance, power, time to market, and ecosystem stickiness." },
      implication: { zh: "按时换代支撑定价；延期或替代方案会侵蚀份额。", en: "On-time transitions support pricing; delays or substitutes erode share." },
      query: "semiconductor product cycle performance power competition market share",
    },
    {
      id: "export-controls",
      name: { zh: "出口管制与市场准入", en: "Export controls and market access" },
      companyExposure: { zh: "高端产品可售市场、许可证及产品降规。", en: "Addressable markets, licensing, and product redesigns for advanced chips." },
      implication: { zh: "规则变化可迅速改变收入可达性、库存和研发优先级。", en: "Rule changes can quickly alter revenue access, inventory, and R&D priorities." },
      query: "semiconductor export controls licensing AI chips market access",
    },
  ],
  peers: [
    { ticker: "AMD", cik: "0000002488", name: "Advanced Micro Devices", rationale: { zh: "AI 加速器、CPU 与数据中心可比。", en: "AI accelerator, CPU, and data-center comparator." } },
    { ticker: "AVGO", cik: "0001730168", name: "Broadcom", rationale: { zh: "定制 AI、网络与高现金转化可比。", en: "Custom AI, networking, and high cash-conversion comparator." } },
    { ticker: "INTC", cik: "0000050863", name: "Intel", rationale: { zh: "CPU、制造资本强度和晶圆代工可比。", en: "CPU, manufacturing intensity, and foundry comparator." } },
    { ticker: "TSM", cik: "0001046179", name: "TSMC", rationale: { zh: "先进制程产能与资本周期可比。", en: "Advanced-node capacity and capital-cycle comparator." } },
  ],
  valuation: {
    method: { zh: "情景 EV / 营收，并以 FCF 交叉核对", en: "Scenario EV / revenue with an FCF cross-check" },
    formula: { zh: "模型隐含企业价值 = 情景营收 × 假设 EV/营收倍数", en: "Model-implied enterprise value = scenario revenue × assumed EV/revenue multiple" },
    multipleLabel: "EV / Revenue",
    multiples: { bear: 6, base: 9, bull: 12 },
    metric: "revenue",
  },
  risks: [
    { zh: "AI 资本开支或云客户订单进入消化期。", en: "AI capex or cloud orders enter a digestion phase." },
    { zh: "产品延期、良率、封装或 HBM 供给限制交付。", en: "Product delay, yield, packaging, or HBM supply constrains shipments." },
    { zh: "客户自研芯片或竞争产品削弱定价和市场份额。", en: "Custom silicon or competing products weaken pricing and share." },
    { zh: "出口管制扩大导致市场受限、库存或产品重设。", en: "Broader export controls cause market restrictions, inventory, or redesigns." },
  ],
  catalysts: {
    operating: [
      { zh: "新架构按期量产且供给瓶颈缓解。", en: "On-time volume ramp of a new architecture with easing supply bottlenecks." },
      { zh: "AI / 数据中心收入和毛利率超出可见性。", en: "AI/data-center revenue and gross margin exceed visible expectations." },
    ],
    financial: [
      { zh: "营收增长与营运资本共同推动 FCF 转化。", en: "Revenue growth and working capital improve FCF conversion." },
      { zh: "库存周转改善且无重大减值。", en: "Inventory turns improve without material write-downs." },
    ],
    regulatory: [
      { zh: "出口许可证或规则明确扩大可服务市场。", en: "Licensing or rule clarity expands the serviceable market." },
      { zh: "产业补贴或本地化产能改善供应韧性。", en: "Industrial incentives or localized capacity improve supply resilience." },
    ],
  },
  reportGuidance: [
    { zh: "按终端市场拆分增长，避免把全部收入增长归因于 AI。", en: "Bridge growth by end market rather than attributing all revenue growth to AI." },
    { zh: "同时观察毛利率、库存和供给承诺，以识别周期质量。", en: "Read gross margin, inventory, and supply commitments together to assess cycle quality." },
    { zh: "估值应把增长、产品周期、客户集中度与出口限制作为独立敏感度。", en: "Valuation should treat growth, product cadence, customer concentration, and export controls as separate sensitivities." },
  ],
};

const bankPack: SectorPack = {
  id: "banks",
  sector: "financials",
  sectorLabel: { zh: "金融", en: "Financials" },
  subindustryLabel: { zh: "多元化银行", en: "Diversified Banks" },
  sicCodes: ["6021", "6022"],
  coreKpis: [
    {
      id: "net-interest-income",
      label: { zh: "净利息收入", en: "Net interest income" },
      description: { zh: "利息收入减利息支出。", en: "Interest income less interest expense." },
      canonicalMetricId: "net-interest-income",
      definitionIds: ["reported-net-interest-income"],
      availability: "notStandardized",
    },
    {
      id: "net-interest-margin",
      label: { zh: "公司净收益率（NIM 近似）", en: "Firmwide net yield (NIM analogue)" },
      description: {
        zh: "发行人披露的管理口径、FTE 基础平均生息资产净收益率；保留其定义，不静默替换为其他 NIM 口径。",
        en: "Issuer-reported managed-basis net yield on average interest-earning assets on an FTE basis; the definition is preserved rather than silently substituted for another NIM convention.",
      },
      canonicalMetricId: "net-interest-margin",
      definitionIds: ["firmwide-net-yield-on-average-interest-earning-assets-managed-basis"],
      availability: "notStandardized",
    },
    {
      id: "deposits",
      label: { zh: "存款", en: "Deposits" },
      description: { zh: "客户存款余额及融资结构。", en: "Customer deposit balances and funding mix." },
      canonicalMetricId: "deposits",
      definitionIds: ["reported-deposits"],
      availability: "notStandardized",
    },
    {
      id: "deposit-cost",
      label: { zh: "总存款成本", en: "Total deposit cost" },
      description: {
        zh: "发行人披露的总存款平均利率，包括无息存款的融资结构影响。",
        en: "Issuer-reported average interest rate on total deposits, including the funding-mix effect of noninterest-bearing deposits.",
      },
      canonicalMetricId: "deposit-cost",
      definitionIds: ["issuer-reported-total-deposit-average-interest-rate"],
      availability: "notStandardized",
    },
    {
      id: "loan-growth",
      label: { zh: "贷款增长", en: "Loan growth" },
      description: { zh: "贷款及租赁余额同比变化。", en: "Year-over-year change in loans and leases." },
      canonicalMetricId: "loan-growth",
      definitionIds: ["year-over-year-loan-growth"],
      availability: "notStandardized",
    },
    {
      id: "credit-losses",
      label: { zh: "信用损失拨备", en: "Credit-loss provision" },
      description: { zh: "当期贷款、租赁及其他信用损失拨备。", en: "Current provision for loan, lease, and other credit losses." },
      canonicalMetricId: "credit-loss-provision",
      definitionIds: ["reported-credit-loss-provision"],
      availability: "notStandardized",
    },
    {
      id: "net-charge-offs",
      label: { zh: "净核销", en: "Net charge-offs" },
      description: {
        zh: "当期从信用损失准备中核销的贷款净额。",
        en: "Loans charged against the allowance for credit losses, net of recoveries, during the period.",
      },
      canonicalMetricId: "net-charge-offs",
      definitionIds: ["issuer-reported-net-charge-offs"],
      availability: "notStandardized",
    },
    {
      id: "allowance-coverage",
      label: { zh: "拨备覆盖", en: "Allowance coverage" },
      description: { zh: "信用损失准备占贷款余额。", en: "Allowance for credit losses divided by loans." },
      canonicalMetricId: "allowance-coverage",
      definitionIds: ["allowance-over-loans"],
      availability: "notStandardized",
    },
    {
      id: "cet1",
      label: { zh: "CET1 比率", en: "CET1 ratio" },
      description: { zh: "普通股一级资本相对风险加权资产。", en: "Common equity tier 1 capital relative to risk-weighted assets." },
      canonicalMetricId: "cet1-ratio",
      definitionIds: ["standardized-cet1-capital-ratio"],
      availability: "notStandardized",
    },
    {
      id: "liquidity",
      label: { zh: "平均流动性覆盖率", en: "Average liquidity coverage ratio" },
      description: { zh: "发行人披露的公司平均 LCR；需结合 HQLA 与批发融资。", en: "Issuer-reported firm average LCR, to be read with HQLA and wholesale funding." },
      canonicalMetricId: "liquidity-coverage-ratio",
      definitionIds: ["firm-average-liquidity-coverage-ratio"],
      availability: "notStandardized",
    },
    {
      id: "efficiency-ratio",
      label: { zh: "效率比率", en: "Efficiency ratio" },
      description: { zh: "非利息费用占净收入。", en: "Noninterest expense divided by net revenue." },
      canonicalMetricId: "efficiency-ratio",
      definitionIds: ["noninterest-expense-over-net-revenue"],
      availability: "notStandardized",
    },
    {
      id: "roe",
      label: { zh: "普通股权益回报率", en: "Return on common equity" },
      description: { zh: "发行人披露的普通股权益回报率。", en: "Issuer-reported return on common equity." },
      canonicalMetricId: "return-on-common-equity",
      definitionIds: ["issuer-reported-return-on-common-equity"],
      availability: "notStandardized",
    },
    {
      id: "rotce",
      label: { zh: "有形普通股权益回报率", en: "Return on tangible common equity" },
      description: {
        zh: "发行人披露的有形普通股权益回报率；保留其非 GAAP 定义。",
        en: "Issuer-reported return on tangible common equity; the issuer's non-GAAP definition is preserved.",
      },
      canonicalMetricId: "return-on-tangible-common-equity",
      definitionIds: ["issuer-reported-return-on-tangible-common-equity"],
      availability: "notStandardized",
    },
    {
      id: "tangible-book-value",
      label: { zh: "有形账面价值", en: "Tangible book value" },
      description: { zh: "股东权益减商誉和可识别无形资产。", en: "Stockholders' equity less goodwill and identifiable intangible assets." },
      canonicalMetricId: "tangible-book-value",
      definitionIds: ["equity-less-goodwill-and-intangibles"],
      availability: "notStandardized",
    },
    {
      id: "tangible-book-value-per-share",
      label: { zh: "每股有形账面价值", en: "Tangible book value per share" },
      description: {
        zh: "发行人披露的每股有形普通股权益；用于 P/TBV 估值。",
        en: "Issuer-reported tangible common equity per share, used in P/TBV valuation.",
      },
      canonicalMetricId: "tangible-book-value-per-share",
      definitionIds: ["issuer-reported-tangible-book-value-per-share"],
      availability: "notStandardized",
    },
    {
      id: "dividends",
      label: { zh: "现金股息", en: "Cash dividends" },
      description: {
        zh: "当期支付的现金股息，需结合普通股与优先股口径。",
        en: "Cash dividends paid during the period, with common and preferred definitions retained.",
      },
      canonicalMetricId: "dividends",
      definitionIds: ["reported-cash-dividends"],
      availability: "notStandardized",
    },
    {
      id: "share-buybacks",
      label: { zh: "普通股回购", en: "Common-share buybacks" },
      description: {
        zh: "当期用于回购普通股的现金。",
        en: "Cash paid to repurchase common shares during the period.",
      },
      canonicalMetricId: "share-buybacks",
      definitionIds: ["reported-common-share-buybacks"],
      availability: "notStandardized",
    },
    {
      id: "capital-returns",
      label: { zh: "资本回报", en: "Capital returns" },
      description: { zh: "现金股息加普通股回购。", en: "Cash dividends plus common-share repurchases." },
      canonicalMetricId: "capital-returns",
      definitionIds: ["dividends-plus-share-buybacks"],
      availability: "notStandardized",
    },
    {
      id: "investment-banking-fees",
      label: { zh: "投资银行费用", en: "Investment banking fees" },
      description: {
        zh: "合并口径的承销与顾问费用。",
        en: "Consolidated underwriting and advisory fees.",
      },
      canonicalMetricId: "investment-banking-fees",
      definitionIds: ["issuer-reported-investment-banking-fees"],
      availability: "notStandardized",
    },
    {
      id: "trading-revenue",
      label: { zh: "市场业务收入", en: "Markets revenue" },
      description: {
        zh: "固定收益与股票市场业务的总净收入；不等同于单一交易收入科目。",
        en: "Total net revenue from Fixed Income and Equity Markets; it is not equivalent to a single trading-income line item.",
      },
      canonicalMetricId: "trading-revenue",
      definitionIds: ["issuer-reported-markets-revenue"],
      availability: "notStandardized",
    },
  ],
  researchQuestions: [
    { zh: "净利息收入变化来自资产收益率、存款成本还是资产负债表规模？", en: "Is net interest income changing because of asset yields, deposit costs, or balance-sheet size?" },
    { zh: "存款与贷款增长是否改善组合质量，还是提高融资和信用风险？", en: "Do deposit and loan growth improve franchise quality or increase funding and credit risk?" },
    { zh: "拨备、净核销和准备金是否覆盖组合级压力？", en: "Do provisions, net charge-offs, and allowances cover portfolio-level stress?" },
    { zh: "CET1、流动性与盈利能否覆盖股息和回购？", en: "Can CET1, liquidity, and earnings cover dividends and buybacks?" },
    { zh: "ROE 与有形账面增长是否支持估值溢价？", en: "Do ROE and tangible-book growth support the valuation premium?" },
  ],
  marketDrivers: [
    {
      id: "rates-deposits",
      name: { zh: "利率与存款定价", en: "Rates and deposit pricing" },
      companyExposure: { zh: "资产收益率、存款贝塔、净利息收入与净息差。", en: "Asset yields, deposit beta, net interest income, and margin." },
      implication: { zh: "降息和存款重定价速度决定净利息收入路径。", en: "The relative pace of rate cuts and deposit repricing determines net interest income." },
      query: "bank net interest margin deposit growth funding costs rates",
    },
    {
      id: "credit-cycle",
      name: { zh: "信用周期", en: "Credit cycle" },
      companyExposure: { zh: "消费、信用卡、商业地产和公司贷款损失。", en: "Consumer, card, CRE, and corporate loan losses." },
      implication: { zh: "拖欠与核销正常化会消耗拨备前利润和资本。", en: "Delinquency and charge-off normalization can consume pre-provision earnings and capital." },
      query: "bank credit losses CRE consumer delinquencies allowance provision",
    },
    {
      id: "capital-liquidity",
      name: { zh: "资本与流动性", en: "Capital and liquidity" },
      companyExposure: { zh: "CET1、风险加权资产、HQLA、批发融资和分配。", en: "CET1, RWA, HQLA, wholesale funding, and distributions." },
      implication: { zh: "压力期最低资本和存款稳定性约束资本回报。", en: "Trough stress capital and deposit stability constrain capital returns." },
      query: "bank CET1 stress test liquidity capital distributions",
    },
    {
      id: "operating-leverage",
      name: { zh: "经营杠杆与费用", en: "Operating leverage and expense" },
      companyExposure: { zh: "手续费、技术投入、效率比率、欺诈和合规成本。", en: "Fees, technology investment, efficiency, fraud, and compliance cost." },
      implication: { zh: "收入增长只有在信用和运营成本后转化为 ROE 才有价值。", en: "Revenue growth matters only when it converts to ROE after credit and operating costs." },
      query: "bank earnings efficiency ratio operating risk cyber fraud compliance",
    },
  ],
  peers: [
    { ticker: "BAC", cik: "0000070858", name: "Bank of America", rationale: { zh: "大型美国消费与企业银行可比。", en: "Large U.S. consumer and corporate bank comparator." } },
    { ticker: "C", cik: "0000831001", name: "Citigroup", rationale: { zh: "全球银行与资本重组可比。", en: "Global bank and capital-restructuring comparator." } },
    { ticker: "WFC", cik: "0000072971", name: "Wells Fargo", rationale: { zh: "存款、消费银行与效率可比。", en: "Deposit, consumer-bank, and efficiency comparator." } },
    { ticker: "GS", cik: "0000886982", name: "Goldman Sachs", rationale: { zh: "市场业务与投行业务可比。", en: "Markets and investment-banking comparator." } },
  ],
  valuation: {
    method: { zh: "情景 P / 有形账面价值", en: "Scenario price / tangible book value" },
    formula: { zh: "模型隐含股权价值 = 情景有形账面价值 × 假设 P/TBV 倍数", en: "Model-implied equity value = scenario tangible book value × assumed P/TBV multiple" },
    multipleLabel: "P / TBV",
    multiples: { bear: 1.2, base: 1.7, bull: 2.2 },
    metric: "tangibleBook",
  },
  risks: [
    { zh: "存款成本下降慢于资产收益率，压缩净息差。", en: "Deposit costs fall more slowly than asset yields, compressing net interest margin." },
    { zh: "消费、商业地产或公司信用损失超过拨备。", en: "Consumer, CRE, or corporate credit losses exceed allowances." },
    { zh: "RWA 增长、压力资本或监管变化限制回购。", en: "RWA growth, stress capital, or regulatory change constrains buybacks." },
    { zh: "市场、网络、欺诈或合规事件造成重大损失。", en: "Market, cyber, fraud, or compliance events cause material losses." },
  ],
  catalysts: {
    operating: [
      { zh: "存款成本改善带动净利息收入上修。", en: "Lower deposit costs lead to higher net interest income." },
      { zh: "费用纪律改善效率比率。", en: "Expense discipline improves the efficiency ratio." },
    ],
    financial: [
      { zh: "信用损失低于预期并释放准备金。", en: "Credit losses undershoot expectations and release reserves." },
      { zh: "CET1 盈余支持更高股息或回购。", en: "Surplus CET1 supports higher dividends or buybacks." },
    ],
    regulatory: [
      { zh: "压力测试或资本规则降低约束。", en: "Stress-test or capital-rule outcomes reduce constraints." },
      { zh: "资本市场和并购活动改善费用收入。", en: "Capital-markets and M&A activity improve fee income." },
    ],
  },
  reportGuidance: [
    { zh: "银行不使用工业公司的营收、资本开支或 FCF 模板。", en: "Do not apply industrial-company revenue, capex, or FCF templates to banks." },
    { zh: "把净利息收入、非息收入、信用成本和非息费用分别桥接。", en: "Bridge net interest income, noninterest income, credit cost, and noninterest expense separately." },
    { zh: "估值以有形账面、ROE、资本和信用情景为核心。", en: "Center valuation on tangible book, ROE, capital, and credit scenarios." },
  ],
};

const biopharmaPack: SectorPack = {
  id: "biopharma",
  sector: "healthcare",
  sectorLabel: { zh: "医疗保健", en: "Healthcare" },
  subindustryLabel: { zh: "大型制药", en: "Large-Cap Pharmaceuticals" },
  sicCodes: ["2834"],
  coreKpis: [
    {
      id: "product-revenue",
      label: { zh: "最大产品收入", en: "Largest-product revenue" },
      description: { zh: "年报产品表中收入最高的单一产品；本次为 Mounjaro。", en: "The largest single product in the annual-filing product table; Mounjaro for this validation." },
      canonicalMetricId: "product-revenue",
      definitionIds: ["issuer-reported-mounjaro-total-revenue"],
      availability: "notStandardized",
    },
    {
      id: "product-concentration",
      label: { zh: "Mounjaro / Zepbound 收入集中度", en: "Mounjaro / Zepbound revenue concentration" },
      description: { zh: "发行人披露的两项产品占总营收比例。", en: "Issuer-reported share of total revenue represented by the two products." },
      canonicalMetricId: "product-concentration",
      definitionIds: ["issuer-reported-mounjaro-zepbound-share-of-total-revenue"],
      availability: "notStandardized",
    },
    {
      id: "pipeline-stage",
      label: { zh: "管线阶段", en: "Pipeline stage" },
      description: { zh: "按候选药与适应症记录临床或监管阶段；阶段为文本证据，不转成伪数字。", en: "Clinical or regulatory stage by candidate and indication; text evidence is not converted into a false numeric metric." },
      availability: "notStandardized",
    },
    {
      id: "clinical-milestones",
      label: { zh: "临床里程碑", en: "Clinical milestones" },
      description: { zh: "试验启动、读出、提交、批准或终止，需保留候选药、适应症和日期。", en: "Trial start, readout, submission, approval, or discontinuation with candidate, indication, and date." },
      availability: "notStandardized",
    },
    {
      id: "regulatory-dates",
      label: { zh: "监管日期", en: "Regulatory dates" },
      description: { zh: "监管机构确认的提交或批准日期；公司预计日期只能作为管理层陈述。", en: "Regulator-confirmed submission or approval dates; company-expected dates remain management statements." },
      availability: "notStandardized",
    },
    {
      id: "research-and-development",
      label: { zh: "研发支出", en: "R&D expense" },
      description: { zh: "不含收购在研资产成本的年度研发支出。", en: "Annual research and development expense excluding acquired in-process research cost." },
      canonicalMetricId: "research-and-development",
      definitionIds: ["reported-research-and-development-expense"],
      availability: "notStandardized",
    },
    {
      id: "gross-margin",
      label: { zh: "毛利率", en: "Gross margin" },
      description: { zh: "毛利润除以营收；毛利润可由营收减销售成本推导。", en: "Gross profit divided by revenue; gross profit may be derived as revenue less cost of sales." },
      canonicalMetricId: "gross-margin",
      definitionIds: ["gross-profit-over-revenue"],
      availability: "grossMargin",
    },
    {
      id: "cash-runway",
      label: { zh: "现金跑道", en: "Cash runway" },
      description: { zh: "只有在净现金消耗和可用流动性口径可验证时计算；盈利制药公司不使用现金除以研发的伪跑道。", en: "Calculated only with a verified net-cash-burn and available-liquidity definition; a profitable pharma company does not use cash divided by R&D as false runway." },
      availability: "notStandardized",
    },
    {
      id: "patent-expiry",
      label: { zh: "Mounjaro / Zepbound 美国化合物专利到期", en: "Mounjaro / Zepbound U.S. compound-patent expiry" },
      description: { zh: "发行人估计的美国化合物专利到期年份，不保证独占期持续至该年。", en: "Issuer-estimated U.S. compound-patent expiry year; exclusivity is not guaranteed through that date." },
      canonicalMetricId: "patent-expiry-year",
      definitionIds: ["issuer-estimated-us-compound-patent-expiry-mounjaro-zepbound"],
      availability: "notStandardized",
    },
    {
      id: "risk-adjusted-pipeline-value",
      label: { zh: "风险调整管线价值", en: "Risk-adjusted pipeline value" },
      description: { zh: "需要候选药级成功概率、时间、峰值销售、利润率、成本和折现率；输入不足时不计算。", en: "Requires candidate-level success probability, timing, peak sales, margin, cost, and discount rate; no value is calculated when inputs are insufficient." },
      availability: "notStandardized",
    },
    {
      id: "cash-capex",
      label: { zh: "现金资本开支", en: "Cash capital expenditure" },
      description: { zh: "现金流量表中的物业和设备购买；用于衡量制造扩张的资本强度。", en: "Cash purchases of property and equipment; a measure of manufacturing-expansion intensity." },
      canonicalMetricId: "cash-capex",
      definitionIds: ["issuer-reported-cash-capex", "cash-purchases-property-plant-equipment"],
      availability: "cashCapex",
    },
    {
      id: "fcf",
      label: { zh: "严格自由现金流", en: "Strict free cash flow" },
      description: { zh: "经营现金流减现金资本开支。", en: "Operating cash flow less cash capital expenditure." },
      canonicalMetricId: "fcf",
      definitionIds: ["ocf-less-cash-capex"],
      availability: "freeCashFlowProxy",
    },
    {
      id: "cash-conversion",
      label: { zh: "自由现金流转化率", en: "Free-cash-flow conversion" },
      description: { zh: "严格自由现金流除以净利润。", en: "Strict free cash flow divided by net income." },
      canonicalMetricId: "cash-conversion",
      definitionIds: ["free-cash-flow-over-net-income"],
      availability: "cashConversion",
    },
  ],
  researchQuestions: [
    { zh: "主要产品增长来自销量、价格、地区、渠道还是供应改善？", en: "Is major-product growth driven by volume, price, geography, channel, or supply?" },
    { zh: "产品和治疗领域集中度是否由新上市产品和管线逐步分散？", en: "Are new launches and pipeline assets reducing product and therapeutic-area concentration?" },
    { zh: "研发支出是否转化为高质量 III 期、提交和批准里程碑？", en: "Is R&D spending converting into high-quality Phase III, submission, and approval milestones?" },
    { zh: "专利、医保谈判、竞争与安全风险如何改变产品生命周期？", en: "How do patents, Medicare negotiation, competition, and safety risk alter product lifecycles?" },
    { zh: "哪些候选药具备足够公开输入支持风险调整估值？", en: "Which candidates have enough public inputs to support risk-adjusted valuation?" },
  ],
  marketDrivers: [
    {
      id: "pharma-obesity-demand",
      name: { zh: "肥胖与糖尿病需求", en: "Obesity and diabetes demand" },
      companyExposure: { zh: "主要产品收入、销量、实现价格、渠道和供应。", en: "Major-product revenue, volume, realized price, channel, and supply." },
      implication: { zh: "高增长只有在价格、渠道和供应后仍转化为毛利和现金流才具质量。", en: "Growth is high quality only if it converts to margin and cash flow after pricing, channel, and supply effects." },
      query: "obesity diabetes prevalence treatment demand GLP-1",
    },
    {
      id: "pharma-glp1-competition",
      name: { zh: "GLP-1 竞争", en: "GLP-1 competition" },
      companyExposure: { zh: "注射与口服药物的疗效、便利性、价格和准入。", en: "Injectable and oral efficacy, convenience, price, and access." },
      implication: { zh: "多剂型竞争可能扩大类别，也可能压低份额和实现价格。", en: "Multi-modality competition can expand the category while pressuring share and realized price." },
      query: "oral semaglutide injectable GLP-1 competition obesity approval",
    },
    {
      id: "pharma-pipeline",
      name: { zh: "口服与注射管线", en: "Oral and injectable pipeline" },
      companyExposure: { zh: "临床阶段、入组、里程碑、提交、批准和研发效率。", en: "Clinical stage, enrollment, milestones, submissions, approvals, and R&D productivity." },
      implication: { zh: "阶段成功、时间和适应症质量共同决定替代现有产品的能力。", en: "Phase success, timing, and indication quality determine replacement capacity for current products." },
      query: "clinical trials Phase 3 oral injectable pipeline approvals",
    },
    {
      id: "pharma-manufacturing",
      name: { zh: "制造能力", en: "Manufacturing capacity" },
      companyExposure: { zh: "API、制剂、设备、投产时点和资本开支。", en: "API, finished dose, equipment, commissioning, and capital expenditure." },
      implication: { zh: "承诺投资只有在按期投产并转化为可售产品时才解除供应约束。", en: "Committed investment relieves supply constraints only when commissioned on time and converted into saleable output." },
      query: "pharmaceutical manufacturing capacity investment supply",
    },
    {
      id: "pharma-pricing-access",
      name: { zh: "定价与准入", en: "Pricing and access" },
      companyExposure: { zh: "净价格、医保谈判、报销、患者自付和处方可及性。", en: "Net price, Medicare negotiation, reimbursement, patient out-of-pocket cost, and prescription access." },
      implication: { zh: "销量增长可能被实现价格和准入限制抵消。", en: "Volume growth can be offset by realized-price and access pressure." },
      query: "CMS Medicare negotiation drug prices access reimbursement",
    },
    {
      id: "pharma-patent-cycle",
      name: { zh: "专利与生命周期", en: "Patent and lifecycle" },
      companyExposure: { zh: "主要产品专利、数据保护、仿制或生物类似药竞争。", en: "Major-product patents, data protection, generic or biosimilar competition." },
      implication: { zh: "集中度越高，生命周期到期前的新产品替代要求越高。", en: "Higher concentration raises the replacement requirement ahead of lifecycle expiry." },
      query: "biopharma patent expiry product concentration lifecycle competition",
    },
    {
      id: "pharma-rd-productivity",
      name: { zh: "研发强度与生产率", en: "R&D intensity and productivity" },
      companyExposure: { zh: "研发支出、III 期、申报、批准、终止和外部创新。", en: "R&D expense, Phase 3, filings, approvals, discontinuations, and external innovation." },
      implication: { zh: "高研发强度需要以有质量的里程碑、组合更新和现金回报验证。", en: "High R&D intensity requires validation through quality milestones, portfolio renewal, and cash returns." },
      query: "pharma R&D productivity Phase 3 approvals cycle time",
    },
    {
      id: "pharma-oncology",
      name: { zh: "肿瘤业务", en: "Oncology exposure" },
      companyExposure: { zh: "Verzenio、Inluriyo、Jaypirca 与后期肿瘤管线。", en: "Verzenio, Inluriyo, Jaypirca, and late-stage oncology pipeline." },
      implication: { zh: "肿瘤组合可分散减重药集中度，但当前规模和生命周期需要分别判断。", en: "Oncology can diversify obesity-drug concentration, but current scale and lifecycle must be assessed separately." },
      query: "oncology breast cancer approvals pipeline",
    },
    {
      id: "pharma-alzheimers",
      name: { zh: "阿尔茨海默病", en: "Alzheimer's exposure" },
      companyExposure: { zh: "Kisunla 商业化、诊断与输注基础设施、后续管线。", en: "Kisunla commercialization, diagnostic and infusion infrastructure, and follow-on pipeline." },
      implication: { zh: "商业化取决于患者识别、监测、安全性和后续资产，而不只是批准状态。", en: "Commercialization depends on patient identification, monitoring, safety, and follow-on assets, not approval alone." },
      query: "Alzheimer's approval diagnosis infusion treatment pipeline",
    },
    {
      id: "pharma-regulatory",
      name: { zh: "监管里程碑", en: "Regulatory milestones" },
      companyExposure: { zh: "批准、提交、优先审评、突破性疗法和标签扩展。", en: "Approvals, submissions, priority review, breakthrough designation, and label expansion." },
      implication: { zh: "只有监管机构确认的状态才能进入已批准商业价值。", en: "Only regulator-confirmed status enters approved commercial value." },
      query: "FDA approvals submissions regulatory milestones",
    },
    {
      id: "pharma-earnings-valuation",
      name: { zh: "盈利与估值敏感性", en: "Earnings and valuation sensitivity" },
      companyExposure: { zh: "营收增速、实现价格、毛利、研发、资本开支、净债务和估值倍数。", en: "Revenue growth, realized price, gross margin, R&D, capex, net debt, and valuation multiple." },
      implication: { zh: "高估值要求增长、利润和现金流同时兑现；单一管线事件不足以支撑全部溢价。", en: "A high valuation requires simultaneous delivery in growth, margin, and cash flow; one pipeline event cannot support the full premium." },
      query: "large cap pharma earnings margins valuation multiples",
    },
  ],
  peers: [
    { ticker: "NVO", cik: "0000353278", name: "Novo Nordisk", rationale: { zh: "肥胖与糖尿病竞争、口服及注射 GLP-1 可比。", en: "Obesity and diabetes competitor across oral and injectable GLP-1." } },
    { ticker: "MRK", cik: "0000310158", name: "Merck & Co.", rationale: { zh: "大型创新药、肿瘤和集中产品组合可比。", en: "Large innovative-pharma, oncology, and concentrated-product comparator." } },
    { ticker: "ABBV", cik: "0001551152", name: "AbbVie", rationale: { zh: "产品生命周期、免疫与管线替代可比。", en: "Product lifecycle, immunology, and pipeline-replacement comparator." } },
    { ticker: "AZN", cik: "0000901832", name: "AstraZeneca", rationale: { zh: "全球肿瘤与创新管线可比。", en: "Global oncology and innovative-pipeline comparator." } },
    { ticker: "JNJ", cik: "0000200406", name: "Johnson & Johnson", rationale: { zh: "多元大型制药与现金流可比。", en: "Diversified large-pharma and cash-flow comparator." } },
  ],
  valuation: {
    method: { zh: "带日期市场锚定的商业收入 EV / 营收敏感性", en: "Dated-market-anchored commercial-revenue EV / revenue sensitivity" },
    formula: { zh: "企业价值 = 情景营收 × 假设 EV/营收倍数；股权价值 = 企业价值 - 净债务；每股价值 = 股权价值 ÷ 稀释股数；不包含未验证的 rNPV", en: "Enterprise value = scenario revenue × assumed EV/revenue multiple; equity value = enterprise value - net debt; per-share value = equity value / diluted shares; no unverified rNPV is included" },
    multipleLabel: "EV / Revenue",
    multiples: { bear: 14, base: 17, bull: 20 },
    metric: "revenue",
  },
  risks: [
    { zh: "Mounjaro 和 Zepbound 集中度使供应、价格、安全或竞争冲击放大。", en: "Mounjaro and Zepbound concentration magnifies supply, pricing, safety, or competition shocks." },
    { zh: "临床失败、入组延误或监管拒绝削弱管线替代。", en: "Clinical failure, enrollment delay, or regulatory rejection weakens pipeline replacement." },
    { zh: "医保谈判、报销和渠道变化压低实现价格或准入。", en: "Medicare negotiation, reimbursement, and channel changes reduce realized price or access." },
    { zh: "专利挑战、到期或仿制与生物类似药竞争提前侵蚀收入。", en: "Patent challenge, expiry, or generic and biosimilar competition erodes revenue earlier than expected." },
  ],
  catalysts: {
    operating: [
      { zh: "主要产品放量同时改善毛利和经营现金流。", en: "Major-product uptake improves both gross margin and operating cash flow." },
      { zh: "供应扩张解除需求约束且不造成库存失衡。", en: "Supply expansion relieves demand constraints without inventory imbalance." },
    ],
    financial: [
      { zh: "研发效率改善并形成高质量提交或批准。", en: "Improved R&D productivity produces high-quality submissions or approvals." },
      { zh: "新产品收入降低单一产品集中度。", en: "New-product revenue reduces single-product concentration." },
    ],
    regulatory: [
      { zh: "监管批准扩大适应症或患者覆盖。", en: "Regulatory approval expands indications or patient coverage." },
      { zh: "定价与报销结果优于保守情景。", en: "Pricing and reimbursement outcomes exceed conservative scenarios." },
    ],
  },
  reportGuidance: [
    { zh: "把产品收入、集中度、价格、销量和供应分别桥接。", en: "Bridge product revenue, concentration, price, volume, and supply separately." },
    { zh: "商业指标使用报告事实；管线概率、时间和价值必须明确标为假设。", en: "Use reported facts for commercial metrics; label pipeline probability, timing, and value explicitly as assumptions." },
    { zh: "公开输入不足时不计算风险调整管线价值，不用候选药数量替代。", en: "Do not calculate risk-adjusted pipeline value from insufficient public inputs or substitute candidate count." },
  ],
};

const industrialMachineryPack: SectorPack = {
  id: "industrial-machinery",
  sector: "industrials",
  sectorLabel: { zh: "工业", en: "Industrials" },
  subindustryLabel: { zh: "工业机械", en: "Industrial Machinery" },
  sicCodes: ["3519", "3523", "3531", "3711"],
  coreKpis: [
    {
      id: "orders",
      label: { zh: "新增订单", en: "New orders" },
      description: { zh: "扣除取消后的期内新增订单；只有发行人口径和期间可验证时才数值化。", en: "Orders received during the period net of cancellations; numeric only when issuer definition and period are verifiable." },
      availability: "notStandardized",
    },
    {
      id: "backlog",
      label: { zh: "公司认定的确定积压订单", en: "Firm order backlog" },
      description: { zh: "发行人认为确定、截至年末仍未履约的订单金额；不等同已确认营收。", en: "Orders the issuer believes to be firm and unfulfilled at year-end; not recognized revenue." },
      canonicalMetricId: "backlog",
      definitionIds: ["issuer-reported-firm-order-backlog"],
      availability: "notStandardized",
    },
    {
      id: "organic-growth",
      label: { zh: "内生增长", en: "Organic growth" },
      description: { zh: "剔除并购和汇率后的可比增长；CAT 未提供统一 FY2025 内生增长数值，因此不以营收增长替代。", en: "Comparable growth excluding acquisitions and currency; CAT did not provide one uniform FY2025 organic-growth value, so revenue growth is not substituted." },
      availability: "notStandardized",
    },
    {
      id: "price-cost",
      label: { zh: "价格 / 制造成本利润影响", en: "Price / manufacturing-cost profit impact" },
      description: { zh: "全年价格实现影响加制造成本影响；两个输入均保留发行人利润桥定义和符号。", en: "Full-year price-realization impact plus manufacturing-cost impact, preserving issuer bridge definitions and signs." },
      canonicalMetricId: "price-cost-impact",
      definitionIds: ["price-realization-plus-manufacturing-cost-impact"],
      availability: "notStandardized",
    },
    {
      id: "segment-margin",
      label: { zh: "Power & Energy 分部利润率", en: "Power & Energy segment profit margin" },
      description: { zh: "分部利润占分部总销售额比例；与合并营业利润率口径不同。", en: "Segment profit as a percentage of total segment sales; distinct from consolidated operating margin." },
      canonicalMetricId: "segment-margin",
      definitionIds: ["issuer-reported-power-energy-segment-profit-margin"],
      availability: "notStandardized",
    },
    {
      id: "cash-capex",
      label: { zh: "现金资本开支", en: "Cash capex" },
      description: { zh: "购置物业、厂房及设备的现金支出，不含租赁设备购置。", en: "Cash purchases of property, plant, and equipment, excluding equipment acquired for lease." },
      canonicalMetricId: "cash-capex",
      definitionIds: ["cash-purchases-property-plant-equipment"],
      availability: "cashCapex",
    },
    {
      id: "working-capital",
      label: { zh: "营运资本", en: "Working capital" },
      description: { zh: "流动资产减流动负债；需结合金融产品业务和客户预付款解释。", en: "Current assets less current liabilities; interpret with Financial Products and customer advances." },
      canonicalMetricId: "working-capital",
      definitionIds: ["current-assets-less-current-liabilities"],
      availability: "notStandardized",
    },
    {
      id: "fcf-conversion",
      label: { zh: "FCF 转化率", en: "FCF conversion" },
      description: { zh: "严格自由现金流除以净利润，其中 FCF = 合并经营现金流减现金资本开支。", en: "Strict free cash flow divided by net income, where FCF = consolidated operating cash flow less cash capex." },
      canonicalMetricId: "cash-conversion",
      definitionIds: ["free-cash-flow-over-net-income"],
      availability: "notStandardized",
    },
    {
      id: "utilization",
      label: { zh: "产能利用率", en: "Capacity utilization" },
      description: { zh: "公司产出相对可持续产能；行业利用率只用于背景，不冒充 CAT 公司指标。", en: "Company output relative to sustainable capacity; industry utilization is context and is not substituted for a CAT metric." },
      availability: "notStandardized",
    },
    {
      id: "project-execution",
      label: { zh: "一年内预计履约积压占比", en: "Backlog expected within one year" },
      description: { zh: "预计下一年度履约的积压占确定积压比例；表示交付义务，不是完工率。", en: "Backlog expected to be fulfilled in the next year as a share of firm backlog; a delivery obligation, not a completion rate." },
      canonicalMetricId: "near-term-backlog-share",
      definitionIds: ["near-term-backlog-over-total-backlog"],
      availability: "notStandardized",
    },
  ],
  researchQuestions: [
    { zh: "订单、取消和积压转化是否支持下一阶段收入，而非仅推迟交付？", en: "Do orders, cancellations, and backlog conversion support the next revenue phase rather than merely deferring delivery?" },
    { zh: "销量与价格能否覆盖制造成本、关税和分部组合压力？", en: "Can volume and price offset manufacturing cost, tariffs, and segment-mix pressure?" },
    { zh: "利润增长是否通过库存、应收、预付款和资本开支转化为 FCF？", en: "Does profit growth convert into FCF through inventory, receivables, advances, and capex?" },
    { zh: "产能、供应链和项目节点是否足以兑现近期待履约积压？", en: "Can capacity, supply chain, and project milestones support near-term backlog delivery?" },
    { zh: "跨周期 FCF 与执行风险是否支持当前估值假设？", en: "Do through-cycle FCF and execution risk support the valuation assumptions?" },
  ],
  marketDrivers: [
    {
      id: "industrial-order-cycle",
      name: { zh: "订单与积压周期", en: "Order and backlog cycle" },
      companyExposure: { zh: "新增订单、取消、确定积压、预计履约期和设备终端销售。", en: "New orders, cancellations, firm backlog, expected fulfillment, and equipment sales to end users." },
      implication: { zh: "积压只有在取消受控且按计划转化为收入和现金时才具有质量。", en: "Backlog is high quality only when cancellations remain controlled and conversion produces revenue and cash on schedule." },
      query: "manufacturing orders unfilled orders backlog shipments inventories",
    },
    {
      id: "industrial-price-cost",
      name: { zh: "价格、成本与关税", en: "Price, cost, and tariffs" },
      companyExposure: { zh: "价格实现、材料与人工、运费、关税、制造成本和分部组合。", en: "Price realization, materials and labor, freight, tariffs, manufacturing cost, and segment mix." },
      implication: { zh: "收入增长若不能覆盖成本和关税，则积压兑现仍可能稀释利润率。", en: "If growth does not cover cost and tariffs, backlog conversion can still dilute margin." },
      query: "producer prices manufacturing costs tariffs price realization margin",
    },
    {
      id: "industrial-capacity",
      name: { zh: "产能与利用率", en: "Capacity and utilization" },
      companyExposure: { zh: "工厂能力、供应商瓶颈、在制品、交期和资本开支。", en: "Plant capacity, supplier bottlenecks, work in process, lead times, and capex." },
      implication: { zh: "低行业利用率不排除局部瓶颈；公司级交付和库存数据更关键。", en: "Low industry utilization does not preclude local bottlenecks; company delivery and inventory data matter more." },
      query: "manufacturing output capacity utilization capital expenditures",
    },
    {
      id: "industrial-cash-execution",
      name: { zh: "现金转化与执行", en: "Cash conversion and execution" },
      companyExposure: { zh: "营运资本、客户预付款、资本开支、FCF 转化和近期待履约积压。", en: "Working capital, customer advances, capex, FCF conversion, and near-term backlog obligations." },
      implication: { zh: "强劲利润只有在营运资本和交付后转化为现金才支持资本回报。", en: "Strong profit supports capital returns only after working-capital and delivery demands convert into cash." },
      query: "backlog conversion working capital inventory shipments execution cash flow",
    },
  ],
  peers: [
    { ticker: "DE", cik: "0000315189", name: "Deere & Co.", rationale: { zh: "大型周期性设备、经销商与融资模式可比。", en: "Large cyclical equipment, dealer, and captive-finance comparator." } },
    { ticker: "CMI", cik: "0000026172", name: "Cummins", rationale: { zh: "发动机、动力系统与工业终端市场可比。", en: "Engine, power-system, and industrial end-market comparator." } },
    { ticker: "PCAR", cik: "0000075362", name: "PACCAR", rationale: { zh: "重型设备、零部件、经销与金融产品可比。", en: "Heavy equipment, parts, distribution, and financial-products comparator." } },
    { ticker: "TEX", cik: "0000097216", name: "Terex", rationale: { zh: "建筑和物料处理设备周期可比。", en: "Construction and materials-processing equipment cycle comparator." } },
  ],
  valuation: {
    method: { zh: "跨周期 EV / FCF 情景", en: "Through-cycle EV / FCF scenarios" },
    formula: { zh: "模型隐含企业价值 = 情景 FCF × 假设 EV/FCF 倍数", en: "Model-implied enterprise value = scenario FCF × assumed EV/FCF multiple" },
    multipleLabel: "EV / FCF",
    multiples: { bear: 10, base: 14, bull: 18 },
    metric: "freeCashFlow",
  },
  risks: [
    { zh: "订单放缓、取消上升或积压转化延期削弱收入可见性。", en: "Order slowing, rising cancellations, or delayed backlog conversion weakens revenue visibility." },
    { zh: "价格实现不足以覆盖材料、人工、运费和关税，压缩分部利润率。", en: "Price realization fails to cover material, labor, freight, and tariffs, compressing segment margin." },
    { zh: "库存、应收和资本开支占用现金，使利润增长不能转化为 FCF。", en: "Inventory, receivables, and capex consume cash, preventing profit growth from converting into FCF." },
    { zh: "供应链、产能或项目执行失误导致成本超支、质保和客户流失。", en: "Supply-chain, capacity, or project-execution failures cause overruns, warranty costs, and customer loss." },
  ],
  catalysts: {
    operating: [
      { zh: "订单和设备终端销售改善，同时保持取消率和库存受控。", en: "Orders and equipment sales to end users improve while cancellations and inventory remain controlled." },
      { zh: "近期待履约积压按计划转化，且不牺牲分部利润率。", en: "Near-term backlog converts on schedule without sacrificing segment margin." },
    ],
    financial: [
      { zh: "价格成本差改善并带动营业利润率恢复。", en: "The price-cost spread improves and supports operating-margin recovery." },
      { zh: "库存与应收释放推动 FCF 转化高于利润增长。", en: "Inventory and receivable release drives FCF conversion above profit growth." },
    ],
    regulatory: [
      { zh: "关税或贸易成本低于保守情景，改善制造成本。", en: "Tariff or trade costs come in below the conservative case and improve manufacturing cost." },
      { zh: "基础设施、矿业或数据中心项目批准支持设备需求。", en: "Infrastructure, mining, or data-center project approvals support equipment demand." },
    ],
  },
  reportGuidance: [
    { zh: "订单、积压和收入必须分开；积压不是已确认营收。", en: "Keep orders, backlog, and revenue separate; backlog is not recognized revenue." },
    { zh: "价格、销量、汇率、制造成本、关税和分部组合分别桥接。", en: "Bridge price, volume, currency, manufacturing cost, tariffs, and segment mix separately." },
    { zh: "FCF 使用规范经营现金流减现金资本开支，并明确营运资本影响。", en: "Use canonical operating cash flow less cash capex for FCF and disclose working-capital effects." },
  ],
};

const PACKS: Record<SupportedSubindustry, SectorPack> = {
  "integrated-oil-gas": energyPack,
  semiconductors: semiconductorPack,
  banks: bankPack,
  biopharma: biopharmaPack,
  "industrial-machinery": industrialMachineryPack,
};

export function getSectorPack(id: SupportedSubindustry) {
  return PACKS[id];
}

export function listSectorPacks() {
  return Object.values(PACKS);
}
