import {
  ingestSectorResearch,
  SECTOR_RESEARCH_AS_OF_DATE,
  SECTOR_RESEARCH_START_DATE,
  type SectorResearchCandidate,
} from "./sector-learning-pipeline";

export type EvidenceCandidate = SectorResearchCandidate;

const RETRIEVAL_DATE = SECTOR_RESEARCH_AS_OF_DATE;
export const MIN_PUBLICATION_DATE = SECTOR_RESEARCH_START_DATE;

const EVIDENCE_CANDIDATES: EvidenceCandidate[] = [
  {
    id: "eia-steo-july-2026",
    title: "Short-Term Energy Outlook - July 2026",
    publisher: "U.S. Energy Information Administration",
    publicationDate: "2026-07-07",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "government-outlook",
    access: "public",
    sector: "energy",
    subindustry: "integrated-oil-gas",
    geography: ["Global", "US"],
    topic: "Oil balance, prices, refining margins, and natural gas",
    url: "https://www.eia.gov/outlooks/steo/report/index.php",
    currentEvidence: {
      zh: "EIA 的 2026 年 7 月基准预计，全球原油库存将在 2027 年转向累积，Brent 均价由 2026 年的 82 美元/桶降至 2027 年的 65 美元/桶；短期成品油库存偏低使裂解价差仍具支撑。",
      en: "EIA's July 2026 baseline expects global oil inventories to shift toward builds in 2027 and Brent to average $82/b in 2026 and $65/b in 2027; low near-term product inventories still support crack spreads.",
    },
    generalizedMethods: [{
      zh: "把能源供需、库存、价格和宏观假设纳入月度短期预测，并比较基准表与前次预测差异。",
      en: "Combine energy supply, demand, inventories, prices, and macro assumptions in a monthly forecast and compare baseline tables with prior revisions.",
    }],
    investorImplication: {
      zh: "综合能源公司的上游现金流面临中期价格回落风险，而炼化与交易的对冲能力决定盈利韧性。",
      en: "Integrated producers face medium-term upstream price pressure; refining and trading offsets determine earnings resilience.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "iea-oil-2025",
    title: "Oil 2025",
    publisher: "International Energy Agency",
    publicationDate: "2025-06-17",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-outlook",
    access: "public",
    sector: "energy",
    subindustry: "integrated-oil-gas",
    geography: ["Global"],
    topic: "Oil supply, demand, refining, trade, and investment through 2030",
    url: "https://www.iea.org/reports/oil-2025/executive-summary",
    currentEvidence: {
      zh: "IEA 认为至 2030 年油市驱动因素正在改变：中国石油需求可能在本十年见顶，美国供应增速放缓，而 OPEC+ 增产与地缘政治使供需和价格路径更不稳定。",
      en: "IEA sees oil-market drivers changing through 2030: Chinese oil demand may peak this decade, U.S. supply growth is slowing, and OPEC+ supply policy plus geopolitics widen the range of price outcomes.",
    },
    generalizedMethods: [{
      zh: "按燃料、行业和地区预测需求，并结合已规划上游及炼化项目评估供应、产能和贸易。",
      en: "Forecast demand by fuel, sector, and region, then evaluate supply, capacity, and trade using planned upstream and refining projects.",
    }],
    investorImplication: {
      zh: "公司价值更依赖低成本资源、项目兑现与资本纪律，而不能只外推单一现货价格。",
      en: "Company value depends increasingly on low-cost resources, project delivery, and capital discipline rather than extrapolating one spot price.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "iea-gas-2025",
    title: "Gas 2025",
    publisher: "International Energy Agency",
    publicationDate: "2025-10-27",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-outlook",
    access: "public",
    sector: "energy",
    subindustry: "integrated-oil-gas",
    geography: ["Global"],
    topic: "LNG capacity, contracts, supply security, and pricing through 2030",
    url: "https://www.iea.org/reports/gas-2025",
    currentEvidence: {
      zh: "IEA 预计到 2030 年全球将新增约 3,000 亿立方米/年的 LNG 出口产能，合同趋向更灵活和更多元定价，可能改善供应安全并重塑区域价差。",
      en: "IEA expects roughly 300 bcm per year of LNG export capacity to be added by 2030, with contracts becoming more flexible and pricing more diverse, potentially improving security and reshaping regional spreads.",
    },
    generalizedMethods: [{
      zh: "结合 LNG 项目、合同数据库和供应安全情景，评估中期全球供需与贸易。",
      en: "Assess medium-term global supply, demand, and trade using LNG projects, contract data, and supply-security scenarios.",
    }],
    investorImplication: {
      zh: "LNG 组合的合同结构、目的地灵活性和项目成本将比单纯销量增长更能解释回报差异。",
      en: "Contract structure, destination flexibility, and project cost may explain LNG returns better than volume growth alone.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "sia-2025-sales",
    title: "Global Annual Semiconductor Sales Increase 25.6% to $791.7 Billion in 2025",
    publisher: "Semiconductor Industry Association",
    publicationDate: "2026-02-06",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "technology",
    subindustry: "semiconductors",
    geography: ["Global", "US"],
    topic: "Semiconductor sales, logic, memory, and regional demand",
    url: "https://www.semiconductors.org/global-annual-semiconductor-sales-increase-25-6-to-791-7-billion-in-2025/",
    currentEvidence: {
      zh: "SIA 报告 2025 年全球半导体销售额达到 7,917 亿美元，同比增长 25.6%；逻辑和存储增速领先，2026 年行业销售额预计接近 1 万亿美元。",
      en: "SIA reported 2025 global semiconductor sales of $791.7 billion, up 25.6%, led by logic and memory, with industry sales projected to approach $1 trillion in 2026.",
    },
    generalizedMethods: [{
      zh: "用三个月移动平均观察月度销售，并按产品和地区比较年度增速以区分结构与总量。",
      en: "Use three-month moving averages for monthly sales and compare annual growth by product and geography to separate mix from aggregate growth.",
    }],
    investorImplication: {
      zh: "强劲总量支持收入，但逻辑与存储领跑意味着必须按终端市场和产品周期判断增长质量。",
      en: "Strong industry growth supports revenue, but logic and memory leadership makes end-market and product-cycle mix essential to judging quality.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "semi-300mm-april-2026",
    title: "SEMI Projects Double-Digit Growth in Global 300mm Fab Equipment Spending for 2026 and 2027",
    publisher: "SEMI",
    publicationDate: "2026-04-01",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-outlook",
    access: "public",
    sector: "technology",
    subindustry: "semiconductors",
    geography: ["Global", "US", "Europe", "International"],
    topic: "300mm capacity, advanced nodes, memory, and AI investment",
    url: "https://www.semi.org/en/semi-press-release/semi-projects-double-digit-growth-in-global-300mm-fab-equipment-spending-for-2026-and-2027",
    currentEvidence: {
      zh: "SEMI 预计 2026 年全球 300mm 晶圆厂设备支出增长 18% 至 1,330 亿美元，2027 年再增长 14% 至 1,510 亿美元；AI、先进制程和存储是主要驱动。",
      en: "SEMI expects global 300mm fab equipment spending to rise 18% to $133 billion in 2026 and another 14% to $151 billion in 2027, driven by AI, advanced nodes, and memory.",
    },
    generalizedMethods: [{
      zh: "用逐厂项目数据库跟踪新增项目、修订和设备支出，将产能建设映射至制程、存储与终端需求。",
      en: "Track additions, revisions, and equipment spending in a facility-level project database and map capacity buildout to nodes, memory, and end demand.",
    }],
    investorImplication: {
      zh: "供给瓶颈可能缓解，但大规模扩产提高了在需求放缓时的库存、利用率和资本周期风险。",
      en: "Supply bottlenecks may ease, but rapid expansion raises inventory, utilization, and capital-cycle risk if demand slows.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "bis-ai-chip-controls-may-2025",
    title: "Department of Commerce Announces Rescission of AI Diffusion Rule, Strengthens Chip-Related Export Controls",
    publisher: "U.S. Bureau of Industry and Security",
    publicationDate: "2025-05-13",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "technology",
    subindustry: "semiconductors",
    geography: ["US", "Global", "International"],
    topic: "AI-chip export controls, diversion, and market access",
    url: "https://www.bis.gov/press-release/department-commerce-announces-rescission-biden-era-artificial-intelligence-diffusion-rule-strengthens",
    currentEvidence: {
      zh: "美国商务部撤销原 AI 扩散规则，同时加强海外 AI 芯片的风险提示、供应链防转移指导和执法重点；替代规则仍可能改变高端芯片的可服务市场。",
      en: "Commerce rescinded the prior AI Diffusion Rule while strengthening overseas AI-chip risk alerts, supply-chain diversion guidance, and enforcement; replacement rules can still change the serviceable market for advanced chips.",
    },
    generalizedMethods: [{
      zh: "把监管机构公告作为政策事实，区分已生效动作、待发布规则与市场预测。",
      en: "Use regulator announcements as policy facts and distinguish effective actions and pending rules from market forecasts.",
    }],
    investorImplication: {
      zh: "收入可达性、产品降规、库存和客户组合可能随许可规则快速变化，应单列监管情景。",
      en: "Revenue access, product redesigns, inventory, and customer mix can change quickly with licensing rules and warrant a separate regulatory scenario.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "semi-memory-equipment-june-2026",
    title: "SEMI Projects 300mm Memory Equipment Investment to Surpass $50 Billion in 2026",
    publisher: "SEMI",
    publicationDate: "2026-06-29",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-outlook",
    access: "public",
    sector: "technology",
    subindustry: "semiconductors",
    geography: ["Global", "US", "Europe", "International"],
    topic: "HBM, advanced-memory capacity, and cloud-led equipment investment",
    url: "https://www.semi.org/en/semi-press-release/semi-projects-300mm-memory-equipment-investment-to-surpass-50-billion-dollars-in-2026",
    currentEvidence: {
      zh: "SEMI 预计 2026 年全球 300mm 存储设备投资增长 29% 至 520 亿美元，DRAM 设备支出受 HBM 和 DDR5 需求推动；技术迁移和先进制程仍限制有效产能增速。",
      en: "SEMI expects 2026 global 300mm memory-equipment investment to rise 29% to US$52 billion, with DRAM spending supported by HBM and DDR5 demand; technology migration and advanced-node complexity still moderate effective capacity growth.",
    },
    generalizedMethods: [{
      zh: "使用逐厂设备支出和产能项目数据库，将云资本开支、AI 加速器需求与 HBM、DRAM 和 NAND 的技术迁移相互验证。",
      en: "Use facility-level equipment-spending and capacity projects to cross-check cloud capex and AI-accelerator demand against HBM, DRAM, and NAND technology migration.",
    }],
    investorImplication: {
      zh: "HBM 与先进存储的资本开支支持 AI 供应链需求，但设备支出上行不等同于所有芯片厂的收入或利润同步上行。",
      en: "HBM and advanced-memory capex supports AI-supply-chain demand, but higher equipment spending does not imply uniform revenue or margin gains across chip suppliers.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "bis-h200-license-january-2026",
    title: "Department of Commerce Revises License Review Policy for Semiconductors Exported to China",
    publisher: "U.S. Bureau of Industry and Security",
    publicationDate: "2026-01-13",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "technology",
    subindustry: "semiconductors",
    geography: ["US", "International"],
    topic: "Advanced-computing export licensing",
    url: "https://www.bis.gov/press-release/department-commerce-revises-license-review-policy-semiconductors-exported-china",
    currentEvidence: {
      zh: "BIS 将 Nvidia H200、AMD MI325X 及类似芯片对华出口改为满足安全、产能与合规条件后逐案审查，显示高端产品市场准入取决于许可细节。",
      en: "BIS moved China exports of Nvidia H200, AMD MI325X, and similar chips to case-by-case review subject to security, capacity, and compliance conditions, making market access dependent on licensing details.",
    },
    generalizedMethods: [{
      zh: "直接从监管公告记录许可条件、生效时间和适用产品，再将审批速度与产品结构作为独立敏感度。",
      en: "Record licensing conditions, effective timing, and covered products directly from the regulator, then model approval timing and product mix as separate sensitivities.",
    }],
    investorImplication: {
      zh: "投资者需要把获批速度、产品结构和美国客户产能保障作为独立收入敏感度。",
      en: "Investors should model approval timing, product mix, and U.S.-customer capacity safeguards as separate revenue sensitivities.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fed-mpr-july-2026",
    title: "Monetary Policy Report - July 2026",
    publisher: "Board of Governors of the Federal Reserve System",
    publicationDate: "2026-07-10",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "government-outlook",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Interest rates, Treasury yield curve, reserves, and bank liquidity",
    url: "https://www.federalreserve.gov/monetarypolicy/2026-07-mpr-part2.htm",
    currentEvidence: {
      zh: "美联储在 2026 年 7 月货币政策报告中指出，联邦基金目标区间自年初以来维持在 3.50%–3.75%，并以 2 年期和 10 年期国债收益率跟踪利率曲线；银行准备金约为 3.1 万亿美元，仍处于充裕水平。",
      en: "The Federal Reserve's July 2026 Monetary Policy Report said the federal funds target had remained at 3.50%–3.75% since the start of the year, tracked the curve with 2- and 10-year Treasury yields, and reported bank reserves of about US$3.1 trillion at ample levels.",
    },
    generalizedMethods: [{
      zh: "将政策利率、2 年与 10 年国债收益率及准备金水平分开跟踪，再把曲线和流动性变化映射至资产收益率、存款成本与净利息收入。",
      en: "Track the policy rate, 2- and 10-year Treasury yields, and reserve levels separately, then map curve and liquidity changes to asset yields, deposit costs, and net interest income.",
    }],
    investorImplication: {
      zh: "高利率与曲线形态仍是净息差和存款贝塔的核心敏感度，而充裕准备金降低了系统性流动性压力。",
      en: "Elevated rates and curve shape remain core sensitivities for margins and deposit beta, while ample reserves reduce systemic liquidity pressure.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fed-sloos-april-2026",
    title: "The April 2026 Senior Loan Officer Opinion Survey on Bank Lending Practices",
    publisher: "Board of Governors of the Federal Reserve System",
    publicationDate: "2026-05-04",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Loan standards, demand, nonbank financial borrowers, and credit risk",
    url: "https://www.federalreserve.gov/data/sloos/sloos-202604.htm",
    currentEvidence: {
      zh: "2026 年 4 月 SLOOS 显示，银行收紧了各规模企业的工商贷款标准，而需求总体基本不变；对非银金融机构的贷款需求走强，但银行因经济前景和借款人风险而收紧其标准与条款。",
      en: "The April 2026 SLOOS reported tighter C&I standards for firms of all sizes and broadly unchanged demand; demand from nonbank financial institutions strengthened, but banks tightened NDFI standards and terms amid economic and borrower-risk concerns.",
    },
    generalizedMethods: [{
      zh: "按借款人和贷款类别分别跟踪标准、条款与需求的净变化，避免把放贷意愿与实际需求混为一谈。",
      en: "Track net changes in standards, terms, and demand separately by borrower and loan category so lending appetite is not confused with actual demand.",
    }],
    investorImplication: {
      zh: "贷款增长机会并不均衡；信贷筛选趋严可能保护损失率，但会限制部分新增贷款和费用收入。",
      en: "Loan growth opportunities are uneven; tighter selection may protect loss rates while constraining some new lending and fee activity.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fed-fsr-funding-may-2026",
    title: "Financial Stability Report - May 2026: Funding Risks",
    publisher: "Board of Governors of the Federal Reserve System",
    publicationDate: "2026-05-08",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "government-outlook",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Deposit funding, uninsured deposits, high-quality liquid assets, and liquidity risk",
    url: "https://www.federalreserve.gov/publications/2026-may-financial-stability-report-funding-risks.htm",
    currentEvidence: {
      zh: "美联储认为大多数银行的融资风险处于中等水平；未保险存款占资产比重明显低于 2023 年高点，大型银行仍持有稳健的高质量流动资产。",
      en: "The Federal Reserve assessed most banks' funding risk as moderate, with uninsured deposits as a share of assets well below 2023 peaks and large banks maintaining sound high-quality liquid assets.",
    },
    generalizedMethods: [{
      zh: "结合未保险存款占比、存款集中度、流动资产和或有融资来源评估挤兑与再融资风险。",
      en: "Assess run and refinancing risk using uninsured-deposit share, deposit concentration, liquid assets, and contingent funding sources.",
    }],
    investorImplication: {
      zh: "行业流动性压力下降，但个股仍需用存款结构、定价和高质量流动资产验证其资金优势。",
      en: "System liquidity pressure has eased, but issuer funding advantages still require evidence from deposit mix, pricing, and high-quality liquid assets.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fed-bank-capital-proposals-march-2026",
    title: "Statements on Bank Capital Proposals by Chair Jerome H. Powell",
    publisher: "Board of Governors of the Federal Reserve System",
    publicationDate: "2026-03-19",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Basel III capital proposals, AFS marks, and G-SIB surcharge calibration",
    url: "https://www.federalreserve.gov/newsevents/pressreleases/powell-statement-20260319.htm",
    currentEvidence: {
      zh: "美联储提出简化资本合规计算、扩大可供出售证券未实现损益计入资本的适用范围，并调整全球系统重要性银行附加资本框架，同时称大型银行核心资本要求的总体校准将保持不变。",
      en: "The Federal Reserve proposed simplifying capital calculations, expanding recognition of available-for-sale securities marks for more large banks, and recalibrating the G-SIB surcharge while preserving the overall calibration of core capital requirements for the largest banks.",
    },
    generalizedMethods: [{
      zh: "区分提案与最终规则，并将风险权重、市场风险、未实现损益及 G-SIB 附加要求逐项映射至 CET1 需求。",
      en: "Distinguish proposals from final rules and map risk weights, market risk, unrealized marks, and G-SIB surcharges separately to required CET1.",
    }],
    investorImplication: {
      zh: "监管重校准可能释放资本，但最终规则、实施时间和业务组合决定真实回购与增长空间。",
      en: "Regulatory recalibration may release capital, but final rules, timing, and business mix determine actual capacity for buybacks and growth.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "occ-bank-trading-q1-2026",
    title: "Quarterly Report on Bank Trading and Derivatives Activities - First Quarter 2026",
    publisher: "Office of the Comptroller of the Currency",
    publicationDate: "2026-06-30",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Bank trading revenue, derivatives, concentration, and market risk",
    url: "https://www.occ.treas.gov/publications-and-resources/publications/quarterly-report-on-bank-trading-and-derivatives-activities/files/q1-2026-derivatives-quarterly.html",
    currentEvidence: {
      zh: "OCC 报告 2026 年第一季度美国商业银行交易收入为 163 亿美元，环比增长 11.4%、同比增长 5.6%；四家大型银行持有行业衍生品名义金额的 79.1%，利率产品占总名义金额的 68.5%。",
      en: "The OCC reported first-quarter 2026 U.S. commercial-bank trading revenue of US$16.3 billion, up 11.4% sequentially and 5.6% year over year; four large banks held 79.1% of industry derivative notional and interest-rate products represented 68.5% of notional.",
    },
    generalizedMethods: [{
      zh: "同时比较交易收入、产品结构、名义金额、净当前信用敞口和机构集中度，避免用名义金额代替真实风险。",
      en: "Compare trading revenue, product mix, notional amounts, net current credit exposure, and institution concentration together rather than treating notional as risk.",
    }],
    investorImplication: {
      zh: "活跃市场可推动交易收入，但集中度、对手方风险和波动性使其不应被视为稳定的利差型收入。",
      en: "Active markets can lift trading revenue, but concentration, counterparty exposure, and volatility mean it should not be valued like stable spread income.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fdic-qbp-q1-2026",
    title: "Quarterly Banking Profile - Q1 2026",
    publisher: "Federal Deposit Insurance Corporation",
    publicationDate: "2026-05-27",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Bank earnings, net interest margin, deposits, loans, capital, liquidity, and credit quality",
    url: "https://www.fdic.gov/quarterly-banking-profile/quarterly-banking-profile-q1-2026",
    currentEvidence: {
      zh: "FDIC 报告 2026 年第一季度行业净息差环比下降 8 个基点至 3.31%，国内存款增长 2.1%，贷款环比增长 1.6%；资本和流动性仍然强健，但部分商业地产与消费组合拖欠率偏高。",
      en: "The FDIC reported that first-quarter 2026 industry net interest margin fell 8 basis points sequentially to 3.31%, domestic deposits grew 2.1%, and loans grew 1.6%; capital and liquidity remained strong while some CRE and consumer delinquencies stayed elevated.",
    },
    generalizedMethods: [{
      zh: "用监管报表构建净息差、存贷款增长、资产质量、资本和流动性的季度同业基准，并保留口径变化说明。",
      en: "Build quarterly peer benchmarks for margin, deposit and loan growth, asset quality, capital, and liquidity from regulatory reports while retaining definition-change notes.",
    }],
    investorImplication: {
      zh: "个股超额收益需要区分行业利差回落与自身存款成本、贷款组合和信用表现。",
      en: "Company outperformance requires separating industry margin pressure from issuer-specific deposit cost, loan mix, and credit performance.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "occ-sarp-spring-2026",
    title: "Semiannual Risk Perspective, Spring 2026",
    publisher: "Office of the Comptroller of the Currency",
    publicationDate: "2026-05-07",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Bank credit, market, operational, compliance, liquidity, and technology risk",
    url: "https://www.occ.treas.gov/publications-and-resources/publications/semiannual-risk-perspective/files/semiannual-risk-perspective-spring-2026.html",
    currentEvidence: {
      zh: "OCC 认为 2025 年银行盈利受贷款增长和融资成本下降支持，资本与流动性处于历史高位；商业地产再融资、私人信贷、部分消费拖欠、网络安全与欺诈仍需监测。",
      en: "The OCC said 2025 bank earnings benefited from loan growth and lower funding costs while capital and liquidity remained high by historical standards; CRE refinancing, private credit, selected consumer delinquencies, cyber risk, and fraud require monitoring.",
    },
    generalizedMethods: [{
      zh: "把信用、市场、操作和合规风险分开评估，并用资本、流动性和盈利缓冲判断各风险能否被吸收。",
      en: "Assess credit, market, operational, and compliance risks separately, then test whether capital, liquidity, and earnings buffers can absorb them.",
    }],
    investorImplication: {
      zh: "低损失率不能替代组合级压力测试；资本回报必须在信用正常化和操作风险成本后评估。",
      en: "Low current loss rates do not replace portfolio stress tests; capital returns should be judged after credit normalization and operational-risk costs.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fed-stress-test-2026",
    title: "2026 Federal Reserve Supervisory Stress Test Results",
    publisher: "Board of Governors of the Federal Reserve System",
    publicationDate: "2026-06-24",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "government-outlook",
    access: "public",
    sector: "financials",
    subindustry: "banks",
    geography: ["US"],
    topic: "Large-bank stress losses, pre-provision net revenue, CET1, and capital resilience",
    url: "https://www.federalreserve.gov/newsevents/pressreleases/bcreg20260624a.htm",
    currentEvidence: {
      zh: "美联储 2026 年压力测试显示，32 家受测银行在严重衰退情景中承受超过 7,080 亿美元总损失后仍高于最低 CET1 要求，汇总资本比率下降 1.6 个百分点；现行资本要求延续至 2027 年。",
      en: "The Federal Reserve's 2026 stress test found all 32 tested banks remained above minimum CET1 requirements after more than US$708 billion of total losses in a severe-recession scenario, with the aggregate capital ratio declining 1.6 percentage points; current requirements remain through 2027.",
    },
    generalizedMethods: [{
      zh: "在统一严重衰退情景下预测损失、拨备前净收入、费用和资本路径，并以最低 CET1 而非期末资本判断脆弱性。",
      en: "Project losses, pre-provision net revenue, expenses, and capital under a common severe recession and assess resilience using minimum rather than ending CET1.",
    }],
    investorImplication: {
      zh: "估值和分配能力应以压力期最低资本、信用损失和盈利缓冲为约束，而不能只看当前 CET1。",
      en: "Valuation and distributions should be constrained by trough stress capital, credit losses, and earnings buffers rather than current CET1 alone.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "iqvia-global-rd-trends-2025",
    title: "Global Trends in R&D 2025",
    publisher: "IQVIA Institute for Human Data Science",
    publicationDate: "2025-04-15",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-outlook",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["Global", "US", "Europe", "International"],
    topic: "Biopharma funding, trial starts, development productivity, cycle time, and launches",
    url: "https://www.iqvia.com/newsroom/2025/04/stabilization-and-improvement-seen-in-multiple-key-biopharma",
    currentEvidence: {
      zh: "IQVIA 报告显示，2024 年生物医药融资升至 1,020 亿美元，临床试验启动量稳定在 5,318 项，开发效率改善主要来自 III 期成功率上升，但项目间隔仍约占整体开发周期 17 个月。",
      en: "IQVIA reported that 2024 biopharma funding reached $102 billion and trial starts stabilized at 5,318; improved development productivity was driven mainly by higher Phase III success while inter-trial intervals still represented about 17 months of total program time.",
    },
    generalizedMethods: [{
      zh: "同时跟踪融资、试验启动、分期成功率、入组时间、项目间隔和新药上市，避免用单一候选药事件代表整体研发效率。",
      en: "Track funding, trial starts, phase success, enrollment time, inter-trial intervals, and launches together rather than using one candidate event as a proxy for overall R&D productivity.",
    }],
    investorImplication: {
      zh: "管线价值应由阶段、成功率、剩余时间与商业潜力共同决定，不能只按候选药数量估值。",
      en: "Pipeline value should reflect stage, success probability, remaining time, and commercial potential rather than candidate count alone.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fda-novel-drug-approvals-2025",
    title: "Novel Drug Approvals for 2025",
    publisher: "U.S. Food and Drug Administration",
    publicationDate: "2026-07-08",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US"],
    topic: "FDA novel-drug approvals and approval dates",
    url: "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
    currentEvidence: {
      zh: "FDA 的 2025 年清单记录了 46 个从未在美国获批或销售的新药，并逐项列示批准日期和首个获批用途。",
      en: "FDA's 2025 list records 46 drugs never previously approved or marketed in the United States and provides each approval date and initial approved use.",
    },
    generalizedMethods: [{
      zh: "用监管机构批准记录验证里程碑和日期，并把已批准、已提交和临床阶段严格分开。",
      en: "Verify milestones and dates against regulator approval records and keep approved, submitted, and clinical-stage programs distinct.",
    }],
    investorImplication: {
      zh: "监管里程碑只有在状态和适应症得到官方确认后，才能进入商业化或概率调整分析。",
      en: "Regulatory milestones should enter commercialization or probability-adjusted analysis only after status and indication are confirmed by the regulator.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fda-clinical-participation-guidance-2025",
    title: "Enhancing Participation in Clinical Trials — Eligibility Criteria, Enrollment Practices, and Trial Designs",
    publisher: "U.S. Food and Drug Administration",
    publicationDate: "2025-12-15",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US", "Global"],
    topic: "Clinical-trial eligibility, enrollment, representativeness, and trial design",
    url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/enhancing-participation-clinical-trials-eligibility-criteria-enrollment-practices-and-trial-designs",
    currentEvidence: {
      zh: "FDA 的 2025 年最终指南建议申办方通过资格标准、入组实践和试验设计提高临床试验代表性，使安全性和有效性证据更贴近潜在用药人群。",
      en: "FDA's December 2025 final guidance recommends eligibility, enrollment, and trial-design approaches that improve representativeness so safety and effectiveness evidence better reflects likely treated populations.",
    },
    generalizedMethods: [{
      zh: "把入组标准、代表性、适应症人群与试验设计纳入里程碑质量判断，而不只关注读出日期。",
      en: "Include eligibility, representativeness, intended population, and trial design in milestone-quality assessment rather than focusing only on readout dates.",
    }],
    investorImplication: {
      zh: "更广泛的人群证据可能提高商业适用性，但也会影响入组速度、成本和数据解释。",
      en: "Broader population evidence may improve commercial relevance but can also change enrollment speed, cost, and interpretation.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "cms-drug-negotiation-2028-selection",
    title: "CMS Announces Selection of Drugs for Third Cycle of Medicare Drug Price Negotiation Program",
    publisher: "Centers for Medicare & Medicaid Services",
    publicationDate: "2026-01-27",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US"],
    topic: "Medicare drug-price negotiation, payer pressure, and product exposure",
    url: "https://www.cms.gov/newsroom/press-releases/cms-announces-selection-drugs-third-cycle-medicare-drug-price-negotiation-program-including-first",
    currentEvidence: {
      zh: "CMS 选择 15 个药品进入第三轮谈判，谈判在 2026 年进行、价格于 2028 年生效；LLY 的 Trulicity 和 Verzenio 位列其中。",
      en: "CMS selected 15 drugs for the third negotiation cycle, with negotiations in 2026 and prices effective in 2028; Lilly's Trulicity and Verzenio were included.",
    },
    generalizedMethods: [{
      zh: "把药品选择、谈判时间、价格生效时间和产品收入敞口分别记录，再进行定价与生命周期情景。",
      en: "Record drug selection, negotiation timing, price-effective timing, and product-revenue exposure separately before running pricing and lifecycle scenarios.",
    }],
    investorImplication: {
      zh: "产品层定价风险应与专利到期、收入集中度和新产品替代能力共同评估。",
      en: "Product-level pricing risk should be assessed with patent expiry, revenue concentration, and replacement capacity from new products.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fda-oral-wegovy-approval-2025",
    title: "Approval Letter: Wegovy (semaglutide) Tablets",
    publisher: "U.S. Food and Drug Administration",
    publicationDate: "2025-12-22",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US"],
    topic: "Obesity treatment, oral GLP-1 competition, and regulatory approval",
    url: "https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2025/218316Orig1s000ltr.pdf",
    currentEvidence: {
      zh: "FDA 于 2025 年 12 月 22 日批准 Wegovy（司美格鲁肽）片剂，为美国体重管理市场增加了获批的口服 GLP-1 竞争产品；批准事实不等同于对市场份额或销售额的预测。",
      en: "The FDA approved Wegovy (semaglutide) tablets on December 22, 2025, adding an approved oral GLP-1 competitor in the U.S. weight-management market; the approval does not itself establish future market share or sales.",
    },
    generalizedMethods: [{
      zh: "用 FDA 批准函核对剂型、批准日期和监管状态，并将批准事实与发行人的疗效或商业预测分开。",
      en: "Use the FDA approval letter to verify formulation, approval date, and regulatory status, keeping those facts separate from issuer efficacy or commercial forecasts.",
    }],
    investorImplication: {
      zh: "口服剂型扩大了患者和支付方的选择，LLY 的竞争分析需要同时比较给药便利性、标签、准入和实际净价格。",
      en: "An oral formulation broadens patient and payer choice, so LLY competition analysis must compare convenience, labels, access, and realized net pricing.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "cms-medicare-glp1-bridge-april-2026",
    title: "Medicare GLP-1 Bridge: Information for Part D Plans",
    publisher: "Centers for Medicare & Medicaid Services",
    publicationDate: "2026-04-06",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US"],
    topic: "Medicare obesity-drug access, beneficiary copay, manufacturer net price, and eligible formulations",
    url: "https://www.cms.gov/medicare/coverage/prescription-drug-coverage/medicare-glp-1-bridge/information-part-d-plans",
    currentEvidence: {
      zh: "CMS 规定 Medicare GLP-1 Bridge 于 2026 年 7 月 1 日至 2027 年 12 月 31 日运行：符合条件的体重管理产品包括 Foundayo 全部剂型、Wegovy 注射剂与片剂以及仅限 KwikPen 的 Zepbound；制造商净价为每月 245 美元，受益人共付额为 50 美元。",
      en: "CMS states that the Medicare GLP-1 Bridge runs from July 1, 2026 through December 31, 2027: eligible weight-management products include all Foundayo formulations, Wegovy injections and tablets, and Zepbound in KwikPen form only; the manufacturer net price is $245 per month and beneficiary copay is $50.",
    },
    generalizedMethods: [{
      zh: "按适应症、剂型、起止日期、净价和患者共付额拆分准入政策，不把覆盖扩大直接等同于收入增长。",
      en: "Separate access policy by indication, formulation, effective dates, net price, and patient copay rather than equating broader coverage directly with revenue growth.",
    }],
    investorImplication: {
      zh: "Bridge 可能扩大可负担性与用药量，但也形成明确的低净价渠道和剂型组合约束，因此销量与价格影响必须分开评估。",
      en: "The Bridge may expand affordability and treatment volume but also creates an explicit lower-net-price channel and formulation mix constraint, requiring separate volume and price analysis.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "cms-2028-mfp-effectuation-guidance-july-2026",
    title: "Manufacturer Effectuation of the MFP Draft Guidance for 2028",
    publisher: "Centers for Medicare & Medicaid Services",
    publicationDate: "2026-07-16",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US"],
    topic: "Medicare negotiated-price implementation, manufacturer obligations, and reimbursement",
    url: "https://www.cms.gov/newsroom/fact-sheets/manufacturer-effectuation-mfp-draft-guidance-2028-medicare-drug-price-negotiation",
    currentEvidence: {
      zh: "CMS 于 2026 年 7 月 16 日发布 2028 年最高公平价格实施草案指南，说明制造商向符合条件的 Medicare 交易提供谈判价格的流程；Trulicity 与 Verzenio 的最终 2028 年谈判价格尚未在该指南中公布。",
      en: "CMS issued draft guidance on July 16, 2026 describing how manufacturers would make 2028 maximum fair prices available for eligible Medicare transactions; the guidance did not publish final 2028 negotiated prices for Trulicity or Verzenio.",
    },
    generalizedMethods: [{
      zh: "区分药品入选、谈判、最终价格公布和价格实施四个阶段；最终价格缺失时不估算折扣。",
      en: "Distinguish drug selection, negotiation, final-price publication, and implementation; do not estimate discounts while final prices are unavailable.",
    }],
    investorImplication: {
      zh: "谈判暴露已确认，但金额仍不确定；在最终价格公布前，估值应把影响列为情景风险而非精确盈利调整。",
      en: "Negotiation exposure is confirmed but the amount remains uncertain; valuation should treat the impact as a scenario risk rather than a precise earnings adjustment until prices are published.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "lilly-foundayo-approval-april-2026",
    title: "FDA Approves Lilly's Foundayo (orforglipron), the Only GLP-1 Pill for Obesity Taken Without Food and Water Restrictions",
    publisher: "Eli Lilly and Company",
    publicationDate: "2026-04-01",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "regulatory-action",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US"],
    topic: "LLY oral GLP-1 approval, obesity access, launch, and commercial competition",
    url: "https://investor.lilly.com/news-releases/news-release-details/fda-approves-lillys-foundayotm-orforglipron-only-glp-1-pill",
    currentEvidence: {
      zh: "Lilly 于 2026 年 4 月 1 日宣布 FDA 批准口服 GLP-1 Foundayo（orforglipron）用于肥胖或超重成人的长期体重管理，并通过 LillyDirect 上市；价格与疗效描述属于发行人披露，应与 FDA 标签分别验证。",
      en: "Lilly announced on April 1, 2026 that the FDA approved oral GLP-1 Foundayo (orforglipron) for chronic weight management in adults with obesity or overweight and launched it through LillyDirect; issuer pricing and efficacy descriptions require separate confirmation against the FDA label.",
    },
    generalizedMethods: [{
      zh: "把监管批准、标签人群、上市渠道、标价与净价分开记录，并明确哪些信息来自发行人。",
      en: "Record regulatory approval, labeled population, launch channel, list price, and net price separately, clearly identifying issuer-sourced information.",
    }],
    investorImplication: {
      zh: "Foundayo 为 LLY 增加口服剂型与直接渠道，但投资者仍需观察供应、支付方覆盖和对现有注射产品的替代或增量效果。",
      en: "Foundayo adds an oral modality and direct channel for LLY, but investors still need evidence on supply, payer coverage, and whether it substitutes for or adds to injectable demand.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "lilly-indiana-manufacturing-may-2026",
    title: "Lilly Commits an Additional $4.5 Billion Across Indiana Manufacturing Sites",
    publisher: "Eli Lilly and Company",
    publicationDate: "2026-05-06",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-outlook",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["US", "Global"],
    topic: "LLY manufacturing investment, incretin supply, planned capacity, and execution risk",
    url: "https://investor.lilly.com/news-releases/news-release-details/lilly-commits-additional-45-billion-across-indiana-manufacturing",
    currentEvidence: {
      zh: "Lilly 宣布在印第安纳州制造基地追加 45 亿美元投资，并计划于 2027 年启用 Lebanon 原料药基地以支持 Mounjaro、Zepbound、Foundayo 和 retatrutide；这是资本承诺和投产计划，不代表当前产能或已实现产量。",
      en: "Lilly announced an additional $4.5 billion investment across Indiana manufacturing sites and plans to open its Lebanon active-ingredient facility in 2027 to support Mounjaro, Zepbound, Foundayo, and retatrutide; these are capital commitments and commissioning plans, not current capacity or realized output.",
    },
    generalizedMethods: [{
      zh: "将已支出资本、承诺资本、计划投产日期、获批产能与实际产量分开，并对建设、验证和监管延误进行敏感性分析。",
      en: "Separate spent capital, committed capital, planned commissioning, approved capacity, and actual output, with sensitivities for construction, validation, and regulatory delays.",
    }],
    investorImplication: {
      zh: "扩产回应强劲需求并可能缓解供应约束，但高资本强度和投产执行决定增量产能何时转化为收入与现金流。",
      en: "Expansion responds to demand and may ease supply constraints, but capital intensity and execution determine when incremental capacity converts into revenue and cash flow.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "clinicaltrials-remternetug-phase3-may-2026",
    title: "A Study of Remternetug (LY3372993) in Early Symptomatic Alzheimer's Disease (TRAILRUNNER-ALZ 1)",
    publisher: "ClinicalTrials.gov",
    publicationDate: "2026-05-22",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "healthcare",
    subindustry: "biopharma",
    geography: ["Global", "US", "Europe", "International"],
    topic: "Alzheimer's pipeline, Phase 3 status, clinical evidence, and readout risk",
    url: "https://clinicaltrials.gov/study/NCT05463731",
    currentEvidence: {
      zh: "ClinicalTrials.gov 在 2026 年 5 月 22 日更新的记录显示，remternetug 的 III 期 TRAILRUNNER-ALZ 1 已于 2026 年 5 月 12 日完成、实际入组 1,667 人，但登记页尚未发布试验结果。",
      en: "The ClinicalTrials.gov record updated May 22, 2026 shows that the Phase 3 remternetug TRAILRUNNER-ALZ 1 study completed on May 12, 2026 with actual enrollment of 1,667, but no study results were posted in the registry.",
    },
    generalizedMethods: [{
      zh: "仅把注册平台用于核对试验设计、状态、入组和日期；未发布结果时不得推断疗效、获批概率或峰值销售。",
      en: "Use the registry to verify study design, status, enrollment, and dates only; do not infer efficacy, approval probability, or peak sales when results are not posted.",
    }],
    investorImplication: {
      zh: "完成 III 期是临床里程碑，但没有公开结果就不能把 remternetug 计入确定性商业价值；读出质量与安全性仍是关键风险。",
      en: "Phase 3 completion is a milestone, but remternetug should not enter deterministic commercial value without public results; readout quality and safety remain key risks.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "census-m3-may-2026",
    title: "Manufacturers' Shipments, Inventories, & Orders — May 2026",
    publisher: "U.S. Census Bureau",
    publicationDate: "2026-07-02",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "industrials",
    subindustry: "industrial-machinery",
    geography: ["US"],
    topic: "Manufacturing orders, unfilled orders, shipments, inventories, and backlog conversion",
    url: "https://www.census.gov/manufacturing/m3/current/index.html",
    currentEvidence: {
      zh: "美国人口普查局报告，2026 年 5 月制造业新订单环比下降 1.3% 至 6,574 亿美元，但未完成订单连续 23 个月中的第 22 个月上升，增至 1.5795 万亿美元；库存升至 9,620 亿美元。",
      en: "The Census Bureau reported that May 2026 manufacturing new orders fell 1.3% to $657.4 billion, while unfilled orders rose for the twenty-second time in twenty-three months to $1.5795 trillion and inventories increased to $962.0 billion.",
    },
    generalizedMethods: [{
      zh: "用期初积压、净新增订单、确认收入和取消订单构建积压瀑布，并将库存与出货和积压转化交叉核对。",
      en: "Build a backlog waterfall from beginning backlog, net new orders, recognized revenue, and cancellations, then cross-check inventory against shipments and backlog conversion.",
    }],
    investorImplication: {
      zh: "订单动能减弱与积压继续增长可以同时发生；投资者必须区分需求、交付能力和收入确认节奏。",
      en: "Order momentum can weaken while backlog still grows, so investors must separate demand, delivery capacity, and revenue-recognition timing.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "fed-g17-june-2026",
    title: "Industrial Production and Capacity Utilization — May 2026",
    publisher: "Board of Governors of the Federal Reserve System",
    publicationDate: "2026-06-15",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "government-outlook",
    access: "public",
    sector: "industrials",
    subindustry: "industrial-machinery",
    geography: ["US"],
    topic: "Manufacturing output, capacity, and utilization",
    url: "https://www.federalreserve.gov/releases/g17/20260615/default.htm",
    currentEvidence: {
      zh: "美联储 2026 年 6 月 G.17 显示，5 月制造业产出环比持平、同比增长 1.4%，制造业产能利用率为 75.7%，仍低于 1972–2025 年 78.2% 的长期均值。",
      en: "The Federal Reserve's June 2026 G.17 release showed May manufacturing output unchanged sequentially and up 1.4% year over year, with manufacturing utilization at 75.7%, below the 78.2% 1972–2025 average.",
    },
    generalizedMethods: [{
      zh: "把产量指数除以可持续产能得到利用率，并按终端市场和行业比较当前利用率、长期均值与增量产能。",
      en: "Measure utilization as output relative to sustainable capacity and compare current rates, long-run averages, and incremental capacity by market and industry.",
    }],
    investorImplication: {
      zh: "低于长期均值的行业利用率限制普遍定价权，但公司积压、产品组合和产能瓶颈仍可能造成显著个股差异。",
      en: "Below-average industry utilization limits broad pricing power, but company backlog, mix, and bottlenecks can still create large issuer differences.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "bls-ppi-june-2026",
    title: "Producer Price Indexes — June 2026",
    publisher: "U.S. Bureau of Labor Statistics",
    publicationDate: "2026-07-15",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-statistics",
    access: "public",
    sector: "industrials",
    subindustry: "industrial-machinery",
    geography: ["US"],
    topic: "Producer prices, input costs, and price-cost spread",
    url: "https://www.bls.gov/news.release/archives/ppi_07152026.htm",
    currentEvidence: {
      zh: "BLS 报告 2026 年 6 月最终需求 PPI 环比下降 0.3%，但同比仍上涨 5.5%；最终需求商品价格下降 1.4%，而剔除食品、能源和贸易服务后的指数环比上涨 0.1%。",
      en: "BLS reported that June 2026 final-demand producer prices fell 0.3% sequentially but remained 5.5% higher year over year; final-demand goods fell 1.4%, while the index excluding food, energy, and trade services rose 0.1%.",
    },
    generalizedMethods: [{
      zh: "把价格实现、材料、人工、运费、关税和组合分别桥接至利润率，而不是用单一总 PPI 代替公司成本。",
      en: "Bridge price realization, materials, labor, freight, tariffs, and mix separately to margin rather than treating one aggregate PPI as company cost.",
    }],
    investorImplication: {
      zh: "总商品通胀放缓不保证制造成本改善；CAT 的价格成本分析必须继续使用发行人桥接并单列关税。",
      en: "Slower aggregate goods inflation does not guarantee manufacturing-cost relief; CAT's price-cost analysis must retain the issuer bridge and isolate tariffs.",
    },
    relevant: true,
    accessible: true,
  },
  {
    id: "cat-q1-2026-results",
    title: "Caterpillar Reports First-Quarter 2026 Results",
    publisher: "Caterpillar Inc.",
    publicationDate: "2026-04-30",
    retrievalDate: RETRIEVAL_DATE,
    sourceType: "industry-outlook",
    access: "public",
    sector: "industrials",
    subindustry: "industrial-machinery",
    geography: ["Global", "US", "International"],
    topic: "Industrial machinery backlog, order activity, price realization, manufacturing cost, and execution",
    url: "https://www.caterpillar.com/content/dam/caterpillarDotCom/releases/1q26/1q26-caterpillar-inc-financial-results.pdf",
    currentEvidence: {
      zh: "Caterpillar 报告 2026 年第一季度销售和收入增长 22% 至 174.15 亿美元，其中销量贡献 23.18 亿美元、价格实现贡献 4.26 亿美元；制造成本带来 7.10 亿美元不利影响，公司称积压订单创纪录。",
      en: "Caterpillar reported first-quarter 2026 sales and revenues up 22% to $17.415 billion, including $2.318 billion from volume and $426 million from price realization; manufacturing costs were a $710 million headwind and management described backlog as a record.",
    },
    generalizedMethods: [{
      zh: "用销量、价格、汇率、制造成本、费用和分部组合重建销售与利润桥，并将积压与实际交付相互验证。",
      en: "Rebuild sales and profit through volume, price, currency, manufacturing cost, expense, and segment mix, then validate backlog against actual delivery.",
    }],
    investorImplication: {
      zh: "强劲订单与销量并不自动带来利润率扩张；关税、制造成本和分部组合决定积压兑现的盈利质量。",
      en: "Strong orders and volume do not automatically expand margin; tariffs, manufacturing cost, and segment mix determine the earnings quality of backlog conversion.",
    },
    relevant: true,
    accessible: true,
  },
];

export function screenSectorEvidence(
  candidates: EvidenceCandidate[],
  currentDate = SECTOR_RESEARCH_AS_OF_DATE,
) {
  return ingestSectorResearch(candidates, currentDate).sources;
}

export const SECTOR_LEARNING_CORPUS =
  ingestSectorResearch(EVIDENCE_CANDIDATES);

export const CURRENT_SECTOR_EVIDENCE =
  SECTOR_LEARNING_CORPUS.sources;
