import type { ClassificationCandidate } from "../types";

export const DATA_CENTER_PACK = {
  packId: "data-center-infrastructure",
  label: "Data Center Infrastructure",
  status: "validated" as const,
  keywords: ["data center", "datacenter", "colocation", "cloud infrastructure"],
  limitations: [
    "Government classification systems do not provide one exact category for the full commercial data-center market.",
    "NAICS 518210 covers computing infrastructure and hosting activities but excludes parts of construction, equipment, power, and real-estate value chains.",
    "BEA and macroeconomic series are adjacent-industry or infrastructure proxies unless explicitly identified as direct indicators.",
  ],
  candidates: [
    {
      mappingId: "dc-naics-518210",
      kind: "naics",
      code: "518210",
      officialLabel: "Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services",
      description: "Operating establishments primarily engaged in computing infrastructure, data processing, web hosting, and related services.",
      providerId: "census",
      includedScope: "Direct operating footprint for U.S. computing infrastructure and hosting establishments",
      knownExclusions: "Dedicated construction, power equipment, cooling equipment, semiconductors, and data-center real estate held in other classifications",
      confidence: "high",
      reason: "Closest direct six-digit NAICS category for the operating data-center and hosting footprint",
      selected: true,
      isProxy: false,
    },
    {
      mappingId: "dc-bea-514",
      kind: "beaIndustry",
      code: "514",
      officialLabel: "Data processing, internet publishing, and other information services",
      description: "BEA industry aggregation used for gross-output and value-added context.",
      providerId: "bea",
      includedScope: "Broader information-services economic footprint",
      knownExclusions: "Not a commercial data-center market definition and includes adjacent information services",
      confidence: "medium",
      reason: "Provides a transparent public-data economic proxy when direct commercial revenue is unavailable",
      selected: true,
      isProxy: true,
    },
    {
      mappingId: "dc-fred-fedfunds",
      kind: "fredSeries",
      code: "FEDFUNDS",
      officialLabel: "Federal Funds Effective Rate",
      description: "Monthly financing-environment indicator.",
      providerId: "fred",
      includedScope: "Interest-rate and financing environment",
      knownExclusions: "Does not measure project-level financing costs",
      confidence: "high",
      reason: "Capital-intensive infrastructure demand is sensitive to the cost and availability of capital",
      selected: true,
      isProxy: true,
    },
    {
      mappingId: "dc-fred-ppi",
      kind: "fredSeries",
      code: "PCU518210518210",
      officialLabel: "Producer Price Index by Industry: Data Processing, Hosting, and Related Services",
      description: "Industry price trend from the Producer Price Index program, distributed through FRED.",
      providerId: "fred",
      includedScope: "Price trend for the closest direct service-industry classification",
      knownExclusions: "Price index is not revenue, demand volume, or commercial market size",
      confidence: "medium",
      reason: "Provides an official price indicator aligned to NAICS 518210",
      selected: true,
      isProxy: true,
    },
    {
      mappingId: "dc-census-cbp",
      kind: "censusDataset",
      code: "cbp",
      officialLabel: "County Business Patterns",
      description: "Annual establishment, employment, and payroll statistics by industry and geography.",
      providerId: "census",
      includedScope: "Employer-establishment footprint for confirmed NAICS mappings",
      knownExclusions: "Establishments are not companies; nonemployer businesses are not included",
      confidence: "high",
      reason: "Official source for establishment, employment, payroll, and regional concentration analysis",
      selected: true,
      isProxy: false,
    },
    {
      mappingId: "dc-bls-employment",
      kind: "blsSeries",
      code: "CEU5051821001",
      officialLabel: "All Employees: Data Processing, Hosting, and Related Services",
      description: "BLS employment series for the closest direct service-industry classification.",
      providerId: "bls",
      includedScope: "National employment trend for the confirmed industry scope",
      knownExclusions: "Does not include construction, equipment, real estate, or power workers classified elsewhere",
      confidence: "medium",
      reason: "Provides a labor-market trend that complements Census annual employer statistics",
      selected: false,
      isProxy: true,
    },
  ] satisfies ClassificationCandidate[],
};
