import type {
  ComparisonCriterion,
  FocusArea,
  MarketLocale,
  MarketMode,
  ProviderExecutionStatus,
} from "./types";

export const MASON_COPY = {
  en: {
    agent: "Mason",
    role: "Market & Industry Analyst",
    workflow: "Official Data Market Analysis",
    heroTitle: "What market should Mason analyze",
    heroSubheading: "Use official public data to analyze an industry, trend, or comparison",
    disclosure: [
      "Mason uses official public datasets and user-confirmed industry mappings to analyze market conditions",
      "Public-data indicators may not correspond exactly to the commercial definition of a market",
    ],
    modes: { analyze: "Analyze", trend: "Trend", compare: "Compare" } satisfies Record<MarketMode, string>,
    buttons: {
      assign: "Assign to Mason",
      confirm: "Confirm data scope",
      cancel: "Cancel analysis",
      retry: "Retry official data",
      edit: "Edit research scope",
      markdown: "Download Markdown",
      pdf: "Download PDF",
      downloadingPdf: "Preparing PDF",
      print: "Print-friendly view",
      addMapping: "Add official code",
    },
    headings: {
      scope: "Research scope",
      focus: "Focus areas",
      companies: "Relevant Public Companies or Tickers",
      confirm: "Confirm the market definition",
      proposedNaics: "Proposed NAICS mappings",
      proposedBea: "Proposed BEA mappings",
      proposedFred: "Proposed FRED series",
      proposedCensus: "Proposed Census datasets",
      proposedOther: "Other official mappings",
      providerPlan: "Official data provider plan",
      providerStatus: "Provider status",
      dataCoverage: "Data Coverage",
      methodology: "Methodology",
      limitations: "Limitations",
      references: "References",
      report: "Mason’s public-data market analysis",
      currentUnavailable: "Current official data unavailable",
    },
    fields: {
      market: "Market or Industry",
      subjectB: "Subject B",
      geography: "Geography",
      geographyB: "Geography B",
      period: "Historical Period",
      analysisYear: "Analysis Year",
      endYear: "End Year",
      question: "Research Question",
      leadingIndicators: "Leading Indicators",
      language: "Language",
      depth: "Report Depth",
      output: "Output Format",
      criteria: "Comparison Criteria",
    },
    progress: {
      inputValidation: "Defining the market",
      classificationSearch: "Matching official classifications",
      scopeConfirmation: "Waiting for scope confirmation",
      providerPlanning: "Building the provider plan",
      dataRetrieval: "Retrieving official data",
      sourceNormalization: "Normalizing metrics",
      evidenceRegistry: "Comparing reported data with calculated indicators",
      metricCalculation: "Calculating compatible indicators",
      compatibilityReview: "Checking whether the proxy is doing too much work",
      analysis: "Analyzing trends",
      reportGeneration: "Drafting the report",
      citationValidation: "Validating references",
      reportQa: "Reviewing data coverage",
    },
    providerStatus: {
      used: "Used",
      unavailable: "Unavailable",
      notRelevant: "Not relevant",
      missingConfiguration: "Missing configuration",
      incomplete: "Incomplete data",
    } satisfies Record<ProviderExecutionStatus, string>,
    mapping: {
      provider: "Provider",
      confidence: "Confidence",
      included: "Included scope",
      exclusions: "Known exclusions",
      reason: "Reason selected",
      proxy: "Public-data proxy",
      direct: "Direct official indicator",
    },
    errors: {
      classification: "Mason could not identify an official classification candidate",
      validation: "Review the highlighted research scope before continuing",
      unavailable: "The configured structured providers did not return usable numerical evidence",
      identicalComparison: "Choose distinct comparison subjects or geographies",
      generic: "Mason could not complete this official-data assignment",
    },
    coverageStatuses: {
      complete: "Complete for selected public-data scope",
      partial: "Partial public-data coverage",
      limited: "Limited proxy-based coverage",
      insufficient: "Insufficient structured data",
    },
    reportLabels: {
      reported: "Reported",
      calculated: "Calculated",
      proxy: "Proxy",
      source: "Source",
      unit: "Unit",
      geography: "Geography",
      period: "Period",
      evidence: "Evidence",
      generatedAt: "Report generated at",
      retrievedAt: "Data retrieved at",
      noEvidence: "Insufficient Evidence",
    },
  },
  zh: {
    agent: "Mason",
    role: "市场与行业分析师",
    workflow: "官方数据市场分析",
    heroTitle: "让 Mason 分析哪个市场",
    heroSubheading: "使用官方公共数据分析行业、趋势或比较对象",
    disclosure: [
      "Mason 使用官方公共数据集和用户确认的行业映射分析市场状况",
      "公共数据指标可能无法完全对应市场的商业定义",
    ],
    modes: { analyze: "分析", trend: "趋势", compare: "比较" } satisfies Record<MarketMode, string>,
    buttons: {
      assign: "交给 Mason",
      confirm: "确认数据范围",
      cancel: "取消分析",
      retry: "重试官方数据",
      edit: "修改研究范围",
      markdown: "下载 Markdown",
      pdf: "下载 PDF",
      downloadingPdf: "正在准备 PDF",
      print: "打印友好视图",
      addMapping: "添加官方代码",
    },
    headings: {
      scope: "研究范围",
      focus: "关注领域",
      companies: "相关上市公司或股票代码",
      confirm: "确认市场定义",
      proposedNaics: "建议的 NAICS 映射",
      proposedBea: "建议的 BEA 映射",
      proposedFred: "建议的 FRED 序列",
      proposedCensus: "建议的 Census 数据集",
      proposedOther: "其他官方映射",
      providerPlan: "官方数据提供商计划",
      providerStatus: "数据提供商状态",
      dataCoverage: "数据覆盖",
      methodology: "方法",
      limitations: "限制",
      references: "参考资料",
      report: "Mason 公共数据市场分析",
      currentUnavailable: "当前官方数据不可用",
    },
    fields: {
      market: "市场或行业",
      subjectB: "比较对象 B",
      geography: "地理范围",
      geographyB: "地理范围 B",
      period: "历史期间",
      analysisYear: "分析年份",
      endYear: "结束年份",
      question: "研究问题",
      leadingIndicators: "领先指标",
      language: "语言",
      depth: "报告深度",
      output: "输出格式",
      criteria: "比较标准",
    },
    progress: {
      inputValidation: "定义市场",
      classificationSearch: "匹配官方分类",
      scopeConfirmation: "等待确认研究范围",
      providerPlanning: "建立数据提供商计划",
      dataRetrieval: "获取官方数据",
      sourceNormalization: "标准化指标",
      evidenceRegistry: "比较报告数据与计算指标",
      metricCalculation: "计算可比指标",
      compatibilityReview: "检查代理指标是否承担过多解释",
      analysis: "分析趋势",
      reportGeneration: "起草报告",
      citationValidation: "验证引用",
      reportQa: "审查数据覆盖",
    },
    providerStatus: {
      used: "已使用",
      unavailable: "不可用",
      notRelevant: "不相关",
      missingConfiguration: "缺少配置",
      incomplete: "数据不完整",
    } satisfies Record<ProviderExecutionStatus, string>,
    mapping: {
      provider: "提供商",
      confidence: "置信度",
      included: "包含范围",
      exclusions: "已知排除项",
      reason: "选择原因",
      proxy: "公共数据代理指标",
      direct: "直接官方指标",
    },
    errors: {
      classification: "Mason 无法识别合适的官方分类候选项",
      validation: "继续前请检查研究范围",
      unavailable: "已配置的结构化数据提供商未返回可用数值证据",
      identicalComparison: "请选择不同的比较对象或地理范围",
      generic: "Mason 暂时无法完成这项官方数据任务",
    },
    coverageStatuses: {
      complete: "所选公共数据范围覆盖完整",
      partial: "公共数据覆盖部分完整",
      limited: "基于代理指标的有限覆盖",
      insufficient: "结构化数据不足",
    },
    reportLabels: {
      reported: "报告值",
      calculated: "计算值",
      proxy: "代理指标",
      source: "来源",
      unit: "单位",
      geography: "地理范围",
      period: "期间",
      evidence: "证据",
      generatedAt: "报告生成时间",
      retrievedAt: "数据获取时间",
      noEvidence: "证据不足",
    },
  },
} as const;

export const FOCUS_AREA_COPY: Record<FocusArea, Record<MarketLocale, string>> = {
  industryFootprint: { en: "Industry footprint", zh: "行业规模" },
  economicContribution: { en: "Economic contribution", zh: "经济贡献" },
  establishments: { en: "Establishments", zh: "经营场所" },
  employment: { en: "Employment", zh: "就业" },
  payrollLaborCost: { en: "Payroll and labor cost", zh: "薪酬与劳动力成本" },
  regionalConcentration: { en: "Regional concentration", zh: "区域集中度" },
  demandIndicators: { en: "Demand indicators", zh: "需求指标" },
  supplyIndicators: { en: "Supply indicators", zh: "供给指标" },
  macroEnvironment: { en: "Macroeconomic environment", zh: "宏观环境" },
  publicCompanyEvidence: { en: "Public-company evidence", zh: "上市公司证据" },
  policyEnvironment: { en: "Policy environment", zh: "政策环境" },
  risks: { en: "Risks", zh: "风险" },
  scenarioOutlook: { en: "Scenario outlook", zh: "情景展望" },
};

export const COMPARISON_CRITERIA_COPY: Record<ComparisonCriterion, Record<MarketLocale, string>> = {
  industryOutput: { en: "Industry output", zh: "行业产出" },
  valueAdded: { en: "Value added", zh: "增加值" },
  establishments: { en: "Establishment count", zh: "经营场所数量" },
  employment: { en: "Employment", zh: "就业" },
  payroll: { en: "Payroll", zh: "薪酬" },
  payrollPerEmployee: { en: "Payroll per employee", zh: "人均薪酬" },
  growth: { en: "Growth", zh: "增长" },
  regionalConcentration: { en: "Regional concentration", zh: "区域集中度" },
  laborCost: { en: "Labor cost", zh: "劳动力成本" },
  macroEnvironment: { en: "Macro environment", zh: "宏观环境" },
  capitalIntensity: { en: "Capital-intensity proxies", zh: "资本密集度代理指标" },
  policyContext: { en: "Policy context", zh: "政策背景" },
  risks: { en: "Risks", zh: "风险" },
};

export const DEFAULT_FOCUS_AREAS: FocusArea[] = [
  "industryFootprint",
  "economicContribution",
  "regionalConcentration",
  "demandIndicators",
  "macroEnvironment",
  "risks",
];

export const DEFAULT_COMPARISON_CRITERIA: ComparisonCriterion[] = [
  "industryOutput",
  "valueAdded",
  "establishments",
  "employment",
  "payrollPerEmployee",
  "growth",
  "regionalConcentration",
  "macroEnvironment",
  "risks",
];

export function masonHeadingValues(locale: MarketLocale) {
  const copy = MASON_COPY[locale];
  return [
    copy.agent,
    copy.role,
    copy.workflow,
    copy.heroTitle,
    copy.heroSubheading,
    ...Object.values(copy.modes),
    ...Object.values(copy.buttons),
    ...Object.values(copy.headings),
    ...Object.values(copy.fields),
    ...Object.values(copy.progress),
    ...Object.values(FOCUS_AREA_COPY).map((value) => value[locale]),
    ...Object.values(COMPARISON_CRITERIA_COPY).map((value) => value[locale]),
  ];
}
